### ISSUE TITLE
Question: Automatic silent token renewals trigger `onSigninCallback`, is it OK? How to distinguish real login from token refresh?

### ISSUE THREAD

**Issue by Kayeeec** [authts/react-oidc-context#1004]
Hi, 

I've discovered that the automatic silent token renewals trigger the `onSigninCallback`. 

**[Q1] Is that a correct behaviour?**  
I couldn't find anything about it in the documentation, and it doesn't seem very logical to me. According to the docs, that hook is supposed to remove the `code` and `state` parameters from the URL and redirect to it. It doesn't need to happen after the token refreshes. I'm just checking if it's not a bug, or could it perhaps be a result of a bad configuration on my side?

**[Q2] Is it ok to use the `user` object, passed to the `onSigninCallback` hook, to distinguish whether it's a real sign-in or just the token renewal?** 
It seems to me that the `user` parameter passed to the `onSigninCallback` is `undefined` when the hook is triggered by the autom. token refresh and defined on a real login. Am I correct? 
I just want to verify if I can rely on this to distinguish the real login and the token refresh within the `onSigninCallback`.

**[Q3] Are there any other unexpected things that trigger the `onSigninCallback` hook?**

---
**_Some background to my questions in case you're interested_**  

I'm fixing this bug in our app where it seemed that some values in local storage got cleared randomly. After some debugging, I discovered that it happened after every silent token refresh. You see, our app needs to clear/reset some local storage values after the user logs in, and we've implemented it inside the `onSigninCallback` hook, thus causing the bug. 
I wanted to fix it like this (just an illustration):
```js
export const OIDC_CONFIG: AuthProviderProps = {
  // our settings...
  onSigninCallback: (user) => {
    if (user === undefined || user === null) return // do nothing if just a token refresh
    const postLoginUrl = getValidPostLoginUrl() // determines the correct URL without code, state etc.
    resetAndInitialiseSomeLocalStorageValues()
    window.location.replace(postLoginUrl)
  },
}
```
So I just want to verify if my assumptions about how it works are correct. 

Another weird thing is that we've discovered this bug just now. The code has been there for almost a year and this started to happen in the last few weeks.  :thinking:

**Comment by pamapa** [comment]
Q1: Yes that is the idea and that is how i use it myself.
See https://github.com/authts/react-oidc-context/blob/ae07cdb2b1529fc922cf7feba4802cf5d9ba0c11/src/AuthProvider.tsx#L31-L45

Q2: For the silent sign in without refresh token you will never get the user object, always void/undefined.
This library calls in that case `signinCallback` of the `oidc-client-ts`, which handles the callback. See https://github.com/authts/oidc-client-ts/blob/b7266eb650391d9e9807af21164874889963f1be/src/UserManager.ts#L315-L333

Q3: `onSigninCallback` is called when auth parameters ((code || error) & state) are found on the url.

**Comment by Kayeeec** [comment]
Thank you for the quick answer. 
I'll make a PR for the documentation when I have a bit more time for it.
