### ISSUE TITLE
Http request to refresh token stuck in loop when using Keycloak

### ISSUE THREAD

**Issue by eugeniosegala** [authts/react-oidc-context#1028]
Hello,

I'm using `react-oidc-context` with Keycloak 22.0.3 and when the Access Token Lifespan is set to 1 minute (or less) it looks like the request which is usually used to request/refresh tokens (`/protocol/openid-connect/token`) is called indefinitely: 

https://github.com/authts/react-oidc-context/assets/29021217/942788f3-cb26-452a-9ca2-829e1104fd9c

![Screenshot 2023-11-21 at 22 40 55](https://github.com/authts/react-oidc-context/assets/29021217/eaf779c2-e29c-4c35-9a09-3579a6135095)

Did anyone else experience this issue? When I set it to 2 minutes, everything seems to be fine.

My config is relatively standard and I did not change any behaviour, example:

```
const oidcConfig = {
  authority: "xxx",
  client_id:"xxx",
  redirect_uri: window.location.href,
  onSigninCallback: () => {
    window.history.replaceState({}, document.title, window.location.pathname);
  },
  userStore: new WebStorageStateStore({ store: oidcInMemoryStorage }),
  monitorSession: true,
};
```

Additionally, I'm running KC in Docker using:

```
docker run --name mykeycloak -p 8080:8080 \
        -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=change_me \
        quay.io/keycloak/keycloak:latest \
        start-dev
```

Thanks!

**Comment by eugeniosegala** [comment]
I may have fixed this using the [accessTokenExpiringNotificationTimeInSeconds](https://github.com/authts/oidc-client-ts/blob/d1bd8ca2d1a9107eff34614ae955f1042443fe1d/src/UserManagerSettings.ts#L153C13-L153C57) from [oidc-client-ts](https://github.com/authts/oidc-client-ts/tree/d1bd8ca2d1a9107eff34614ae955f1042443fe1d).

Can anyone confirm this is the best approach?

**Comment by pamapa** [comment]
I have never tried to reduce the lifespan that short. If possible try to go longer. Is there a specific reason to have it so short?

**Comment by eugeniosegala** [comment]
A one-minute token is highly secure since it minimises the window for potential token misuse or interception. If security is a top priority and the risk of token compromise is high, a short lifespan like this can be beneficial.

I can confirm that the `accessTokenExpiringNotificationTimeInSeconds` worked :)
