### ISSUE TITLE
Use npm distribution tags for upcoming releases

### ISSUE THREAD

**Issue by pschaub** [authts/react-oidc-context#1070]
### Summary
I recently encountered some confusion with our project dependencies listed under `npm outdated`. The confusion stemmed from the inability to distinguish between stable and beta versions. To address this and improve clarity for developers, I propose the adoption of NPM distribution tags.

```sh
$ npm outdated
Package                           Current   Wanted        Latest 
oidc-client-ts                      2.4.0    2.4.0    3.0.0-rc.0
react-oidc-context                  2.3.1    2.3.1  3.0.0-beta.0
```

### Proposal
Implement the use of npm distribution tags, specifically tags like "latest" for stable releases and "beta" or "next" for pre-release versions.

### Why It's Needed
In enterprise environments, stability is paramount. Without clear distinction between stable and beta releases, there's a risk of inadvertently upgrading to a less stable version, potentially introducing bugs or compatibility issues.

Using npm distribution tags would ensure that commands like `npm update` or `npm outdated` reflect the intended usage of the package versions. Developers would easily identify the stability of each version and could avoid updating to a beta release in a production environment.

For more information on NPM distribution tags and their importance in release management, please refer to the official NPM documentation: [Managing Package Distribution Tags](https://docs.npmjs.com/cli/v8/commands/npm-dist-tag).

### Conclusion
Adopting this practice would greatly enhance the developer experience and maintain the integrity of stable projects.

**Comment by pamapa** [comment]
Good point, i have now manually set the latest version. See https://github.com/authts/oidc-client-ts/issues/1316
