### ISSUE TITLE
logout other active tabs

### ISSUE THREAD

**Issue by cocadepoma** [authts/react-oidc-context#1081]
Hello, thank you for this great library.

I am using ZITADEL as an IAM and trying to automatically log out the user when they press the logout button by using a storage listener:
```js
  const checkStatusLocalStorage = async () => {
    const user = localStorage.getItem('oidc.user:<your authority>:<your client id>');

    if (!auth.isAuthenticated && !hasTriedSignin && !user) {
      auth.signoutRedirect();
    }
  };
```

It works fine within the same browser, but I wonder if it is possible to do a workaround by using the underlying library to automatically log out the user without relying on localStorage.

Another question is, is it safe to use localStorage for storing all the information coming from ZITADEL?

Thanks in advance.

**Comment by pamapa** [comment]
> It works fine within the same browser, but I wonder if it is possible to do a workaround by using the underlying library to automatically log out the user without relying on localStorage.

Why not directly call `auth.signoutRedirect();` after `await auth.removeUser();` on the logout button?

> Another question is, is it safe to use localStorage for storing all the information coming from ZITADEL?
Safe enough depends on your requirements, you can google the pro and cons. 

Google: "Advantage of localStorage is its contents cannot be automatically sent anywhere. Therefore, localStorage is immune to cross-site request forgery (CSRF) attacks. On the downside, localStorage is potentially vulnerable to cross-site scripting (XSS) attacks."

As such make sure your application is safe against XSS. And keep the expire time small (e.g. <2h). For sensitive data it makes sense to use the concept of trusted devices in addition to where it is store. This can prevent to usage of a stolen token.

**Comment by soyl3y3nd4** [comment]
> Why not directly call `auth.signoutRedirect();` after `await auth.removeUser();` on the logout button?

This is not firing anything other tabs listen to, so I cannot automatically log out, perhaps I am doing something wrong.

The code for logout is doing this:

```javascript
  const handleLogout = async () => {
    await auth.removeUser();
    auth.signoutRedirect();
    localStorage.clear();
  };
```
I've added the localStorage.clear() to clean all the stuff stored in there, especially all the keys starting with `oidc.<id>`. BTW, what are all of them? sessions? Are they necessary or Is possible to avoid storing them?

In addition, I have this code for the auto sign-in when a user refreshes the page, but this code is not being executed when I log out in another tab, so It's not doing anything.

```javascript
  useEffect(() => {
    if (
      (!hasAuthParams() &&
        !auth.isAuthenticated &&
        !auth.activeNavigator &&
        !auth.isLoading &&
        !hasTriedSignin)
    ) {
      auth.signinRedirect();
      setHasTriedSignin(true);
    }

    checkParams();
  }, [auth, hasTriedSignin]);
```

This is my OIDC config:

```javascript
  const oidcConfig = {
    authority: Environment.oidcIssuer,
    client_id: Environment.oidcClientId,
    redirect_uri: "http://localhost/login",
    post_logout_redirect_uri: Environment.oidcLogout,
    response_type: 'code',
    scope: 'openid profile email offline_access',
    userStore: new WebStorageStateStore({ store: window.localStorage }),
    automaticSilentRenew: true,
    onSigninCallback() {
      // You must provide an implementation of onSigninCallback to oidcConfig to remove the payload
      // from the URL upon successful login.
      // Otherwise if you refresh the page and the payload is still there, signinSilent - which handles renewing your token - won't work.
      window.history.replaceState(
        {},
        document.title,
        window.location.pathname
      );
    },
  };
```

Any idea what's going on with those other tabs that are not being signed off automatically?

Thank you!

**Comment by pamapa** [comment]
Maybe `monitorSession` is what you are looking for. See https://authts.github.io/oidc-client-ts/interfaces/UserManagerSettings.html#monitorSession. Ensure to use [v3.0.0-rc.1](https://github.com/authts/react-oidc-context/releases/tag/v3.0.0-rc.1) of this library because of #1087.

**Comment by Rigel772** [comment]
It is a bit confusing...
With help of ChatGPT:
"""
When auth.removeUser() is called in an application using the oidc-client-ts library, it removes the user's data from the client-side storage, which includes tokens and profile information. However, the ability for a user to log in again without providing a password after this operation is often due to the way web authentication and session management work, particularly with Single Sign-On (SSO) mechanisms and session cookies managed by the Identity Provider (IdP).
"""
... so `removeUser()` does not really logs the user out and that example with button "Log out" is missleading (at least was for me)
When `signoutRedirect()` is called the user is signed out in the authentication backend so it should apply to all other tabs and windows

Please correct me if I am wrong.

**Comment by mparsakia** [comment]
You can achieve the functionality you are looking for by using a [BroadcastChannel ](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel) whenever you call an auth.logout and handle it by listening in other tabs, at least for clearing the state client side.
