### ISSUE TITLE
How to do PKCE authentication callback?

### ISSUE THREAD

**Issue by kpeters-seagull** [authts/react-oidc-context#1094]
I'm trying to do a PKCE authentication flow (as outlined here: https://github.com/authts/oidc-client-ts/blob/main/docs/protocols/authorization-code-grant-with-pkce.md)

I've seen a previous issue that says this is supported by this library, but it's not clear to me how this is done, since the `signinCallback()` method isn't exposed and I don't see any sort of "callbackUrl" property on any of the sign-in methods that are.

How do I make that callback request after authenticating (with something like `auth.signinRedirect()`)?

Edit: After some digging, it looks like this is automatically done if the appropriate parameters are detected in the url. Is that right? But I don't see a way to specify what that callback url should be.

**Comment by pamapa** [comment]
> Edit: After some digging, it looks like this is automatically done if the appropriate parameters are detected in the url. Is that right? But I don't see a way to specify what that callback url should be.

Correct the callback if properly configured is handled within this library. See https://github.com/authts/react-oidc-context/blob/74a09c0304b8e43dc8aa41221b2b9afdc24ba374/src/AuthProvider.tsx#L196_L210

**Comment by kpeters-seagull** [comment]
Thanks. But it doesn't look like the library allows a URL to be specified for that callback, even though the oidc-client-ts does. Would this just be something I have to do myself then if I need to callback to a particular URL?

**Comment by pamapa** [comment]
The callback URL configuration can be passed into like in `oidc-client-ts` via `redirect_uri`...

```tsx
const oidcConfig = {
  authority: "<your authority>",
  client_id: "<your client id>",
  redirect_uri: "<your redirect uri>",
  // ...
};
```

The callback itself is handled within this library. From the README.md:
 - Additionally it intercepts the auth redirects by looking at the query/fragment parameters and acts accordingly. You still need to setup a redirect uri, which must point to your application, but you do not need to create that route.
