### ISSUE TITLE
isAuthenticated still true even silent renew ended with error

### ISSUE THREAD

**Issue by lenaka741** [authts/react-oidc-context#1153]
Hi, 
In my application I have set automaticSilentRenew to true and the token is refreshing without the problem. 
Then I logout in keycloak, so the sessions is not valid anymore.
But my application did not notice it, auth.isAuthenticated is still true, 
even when automatic silent renew failed, I received an error in auth object but isAuthenticated is not changed.
Do you have an idea why isAuthenticated is not updated?

**Comment by rwerg7w230jDF** [comment]
isAuthenticated is true as long there is a valid access token: https://github.com/authts/react-oidc-context/blob/main/src/AuthState.ts#L20

**Comment by rwerg7w230jDF** [comment]
seems like isAuthenticated doesn't get updated on Error: https://github.com/authts/react-oidc-context/blob/a1453191a455e5b77b16f70d838195a078739725/src/reducer.ts#L47

**Comment by pamapa** [comment]
> I guess it's intended

Yes, Please check for error object in that cases...

**Comment by lenaka741** [comment]
Ok, I can relay on error object. Thanks for response.
