### ISSUE TITLE
blank page after successful authentication

### ISSUE THREAD

**Issue by irom77** [authts/react-oidc-context#1200]
Few users getting blank page after successful authentication. Using _"oidc-client-ts": "^2.4.0" and "react-oidc-context": "^2.3.1" and "react-router": "^6.18.0"_ **Uncaught TypeError: t.map is not a function** shows up in console. Any suggestions how to debug it ?

**App.jsx**
```
...
function onSigninCallback() {
    window.location.href = import.meta.env.VITE_REDIRECT_URI
  }
...
return (
    <AuthProvider {...oidcConfig} onSigninCallback={onSigninCallback}>
        <Navbar />
        <div className="container">
        <Routes>
            <Route path="/" element={<Home />}/>
            ….
            <Route path="*" element={<NoPage />} />
        </Routes>
        </div>
    </AuthProvider>              
    )
}
```

**Navbar.jsx**
```
const handleLogin = () => {
    void auth.signinRedirect()
  }
```

**Comment by pamapa** [comment]
Real debugging might be tricky, its probably easier to "debug" via logging..
You can add logging within the underlying library. See https://authts.github.io/oidc-client-ts/#md:logging
Also you should add logging within your custom hooks (e.g. `onSigninCallback`).

As you said it only happens for some users, what is the difference? browser type/version, os,....?

**Comment by irom77** [comment]
I will try that, appreciate. If it does not work for a given user, it gives blank page in all browsers. OS is windows across the board (but I will double check)

**Comment by irom77** [comment]
it was not `react-oidc-context` related, but the way authorization was implemented
