### ISSUE TITLE
Minimal, reproducible example with Keycloak

### ISSUE THREAD

**Issue by zach-betz-hln** [authts/react-oidc-context#1208]
This is not an issue. 

Just sharing this little project, in hopes that others may play with it and get ideas for their own implementations.

Thank you for this library.

Feel free to close this issue at your convenience. 

https://github.com/zach-betz-hln/mre-keycloak-react

**Comment by pamapa** [comment]
This is awesome, thanks for sharing!
I could clone the project as `sample-react-oidc-context-keycloak` within `authts` if you want...

**Comment by zach-betz-hln** [comment]
@pamapa Sure 👍

**Comment by pamapa** [comment]
Here you go: https://github.com/authts/sample-keycloak-react-oidc-context
Feel free to make pull requests. Would be nice if you keep maintaining it...

**Comment by zach-betz-hln** [comment]
I don't like the idea of maintaining duplicate repos, so I've archived my repo and added a link to the one you cloned under the authts namespace. See https://github.com/zach-betz-hln/mre-keycloak-react/commit/07b75ff82f67119b7e5e9e887aa011da76a33125

**Comment by zach-betz-hln** [comment]
@pamapa looks like I need permission to push: 

```
ERROR: Permission to authts/sample-keycloak-react-oidc-context.git denied to zach-betz-hln.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by pamapa** [comment]
You should have now direct access to the new repository, however everything must go through a pull request, no shortcuts via push :-). This ensures the CI is working, thus for others is also working...

**Comment by zach-betz-hln** [comment]
Thanks. And yep, the pull request process sounds good to me. See first one: https://github.com/authts/sample-keycloak-react-oidc-context/pull/2

**Comment by thareekanvarm** [comment]
@zach-betz-hln  @pamapa 

how can i handle this 

({ onLoad: "check-sso", checkLoginIframe: false })

**Comment by zach-betz-hln** [comment]
@thareekanvarm I don't understand your question. 

Also, please open a new issue with your question, and with more details.
