### ISSUE TITLE
void is not valid as a constituent in a union

### ISSUE THREAD

**Issue by mfulton26** [authts/react-oidc-context#1256]
https://github.com/authts/react-oidc-context/blob/8f5d9b47c12831d257eda29c14cab7f1d0134e31/src/AuthProvider.tsx#L42

see [no-invalid-void-type | typescript-eslint](https://typescript-eslint.io/rules/no-invalid-void-type/)

I suggest using `user: User | undefined` or `user?: User` instead of `user: User | void`.

**Comment by pamapa** [comment]
fixed via https://github.com/authts/react-oidc-context/commit/3345125ba96774726561e64db3717805aa610579
