### ISSUE TITLE
Is there a way to stay in http with oidc-client-ts ?

### ISSUE THREAD

**Issue by davidbourrel** [authts/react-oidc-context#1288]
Hello,

My team and I are currently developing an app but we want to stay temporarily in **http** instead of **https**. 

However, http in not a secure context (localhost and https yes) so we have a problem with Crypto.subtle probably called by generateCodeChallenge in :  src/utils/CryptoUtils.ts ([oidc-client-ts](https://github.com/dbfr3qs/oidc-client-ts/blob/main/src/utils/CryptoUtils.ts))

> Crypto.subtle is available only in secure contexts (HTTPS).

Do you thing there is a way to use react-oidc-context (depend of oidc-client-ts) with http or it's not possible ?

Thank you !

**Comment by pamapa** [comment]
That is a browser built int feature and therefore we can not control it, which is good. If you really need something else you would either have to use the older version of this library (v2.3.1) or manually patch that code part yourself by reverting it back to the old behaviour...

**Comment by davidbourrel** [comment]
Downgrade to an older verson doesn't work too, Crypto inteface is there too ^^ Ok we gonna switch to https.

Thank you for your reply !
