### ISSUE TITLE
How to get token

### ISSUE THREAD

**Issue by abdulk1** [authts/react-oidc-context#1305]
I have a React application integrated with this library. I can trigger the auth endpoint by calling signinRedirect. The redirect works. I can sign in and get redirected back to my app as expected. 

Now I need to trigger the token endpoint but the documentation doesn't specify how to do that.

**Comment by zach-betz-hln** [comment]
The `token` endpoint is usually called as part of the `auth.signinRedirect()` [flow](https://github.com/authts/sample-keycloak-react-oidc-context).

Can you say more about what you're looking for? Do you need the `access_token`? Or something else?

**Comment by LethargicDeveloper** [comment]
I believe I have the same or similar question.

Let's say we have a react frontend, an api backend (mine is .net core), and a keycloak server and I want to implement authorization code flow.

My understanding of how the flow should work is the following:
1. User clicks login on the React webapp and is redirected to Keycloak
2. The user logs into keycloak and is redirected back to the valid redirect url (back to the react web app) with an authorization code
3. The react web app sends the authorization code it received from keycloak to the api backend to exchange it for an access token.
4. The frontend uses that access token to make further requests against the api.

My knowledge of oauth/openid connect is pretty surface level. Isn't signinRedirect using more of a hybrid flow, which is less secure? Maybe I'm off base here. I'm trying to figure out how this _should_ work.

**Comment by zach-betz-hln** [comment]
@LethargicDeveloper - if you're using _Authorization Code Grant with Proof Key for Code Exchange (PKCE)_ then this [diagram](https://github.com/authts/oidc-client-ts/blob/main/docs/protocols/authorization-code-grant-with-pkce.md) may help with understanding the flow.

**Comment by idc77** [comment]
Essentially, react-oidc-context handles 3. (and 2. and 1.) automatically.
For 4. here's a snippet I have in my RelayEnvironment.ts (from relay.dev)
```ts
function getUser() {
  let oidcStorage = localStorage.getItem(`oidc.user:${oidcConfig.authority}:${oidcConfig.client_id}`)
  if (!oidcStorage) {
    oidcStorage = sessionStorage.getItem(`oidc.user:${oidcConfig.authority}:${oidcConfig.client_id}`)
    if (!oidcStorage) {
      return null;
    }
  }

  return User.fromStorageString(oidcStorage);
}

const fetchFn: FetchFunction = async (request, variables) => {
  const user = getUser()
  const access_token = user?.access_token

  const headers = new Headers()
  headers.set("Accept", "application/graphql-response+json; charset=utf-8, application/json; charset=utf-8")
  headers.set("Content-Type", "application/json; charset=utf-8")
  if (access_token) {
    headers.set("Authorization", `Bearer ${access_token}`)
  }

  const resp = await fetch(HTTP_ENDPOINT, {
    method: "POST",
    headers: headers,
    body: JSON.stringify({
      query: request.text, // <-- The GraphQL document composed by Relay
      variables,
    }),
  });

  return await resp.json();
};
```
