### ISSUE TITLE
Check Authentication Status outside React Component

### ISSUE THREAD

**Issue by Smoodi** [authts/react-oidc-context#1350]
Hi,
I wanted to use the React OIDC context together with TanStackRouter.
Is there a way to check the authentication status outside of a React Component?
Basically I'd need a way to tell if the user is authenticated in the preLoad function.

Whilst, yes it is possible to just wrap the entire component into a <withAuthenticationRequired> the problem still arises when trying to call an protected API in the loader function that is supposed to fetch required data before loading the actual component. 

See:
https://tanstack.com/router/latest/docs/framework/react/guide/authenticated-routes

Thanks in advance!

**Comment by tarkant** [comment]
Hi! I'm checking in because I'm interested by this too. The project I'm working on uses Tanstack router and I would also need to get the auth state. I've looked through the source of this library and there does not seem to be a simple way to do it.

**Comment by zach-betz-hln** [comment]
Hi @Smoodi have you tried this [section](https://tanstack.com/router/latest/docs/framework/react/guide/authenticated-routes#authentication-using-react-contexthooks) of their docs? 

> If your authentication flow relies on interactions with React context and/or hooks, you'll need to pass down your authentication state to TanStack Router using router.context option.

> React hooks are not meant to be consumed outside of React components. If you need to use a hook outside of a React component, you need to extract the returned state from the hook in a component that wraps your <RouterProvider /> and then pass the returned value down to TanStack Router.

In their snippets, they pass the `useAuth()` hook result to the `context` of the `RouterProvider` - which you could try as well. 

Then in your `beforeLoad` function, access the auth with `context.auth`

**Comment by tarkant** [comment]
Hey @zach-betz-hln  thanks for chiming in!

You're right, here's for future reference what I did to get it to work:

```tsx
/// file __root.tsx
import { createRootRouteWithContext } from '@tanstack/react-router';
import app from '../app';
import { AuthContextProps } from 'react-oidc-context';

interface MyRouterContext {
  auth: AuthContextProps,
}

export const Route = createRootRouteWithContext<MyRouterContext>()({
  component: app,
});

```

In my `main.tsx`

```tsx
/// file main.tsx

// Omitting some imports

// Our project works with a generated root tree
import { routeTree } from './routeTree.gen';
import { AuthProvider, useAuth } from "react-oidc-context";

import { OIDC_CONFIG } from './oidc';

// Create a new router instance
const router = createRouter({
  routeTree,
  context: {
    // auth will initially be undefined
    // We'll be passing down the auth state from within a React component
    auth: undefined!,
  },
});

function InnerApp() {
  const auth = useAuth()
  return <RouterProvider router={router} context={{ auth }} />
}

// Render the app
const rootElement = document.getElementById('root')!;
if (!rootElement.innerHTML) {
  const root = ReactDOM.createRoot(rootElement);
  root.render(
    <StrictMode>
      <AuthProvider {...OIDC_CONFIG}>
        <InnerApp />
      </AuthProvider>
    </StrictMode>
  );
}

```

Finally in a route for example:

```tsx
import { Preferences } from '@/preferences.container';
import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute('/preferences/')({
  beforeLoad: ({ context, location }) => {
    console.log(context, location, context['user']);
  },
  component: () => <Preferences />,
});

```

:warning: I've noticed a small drawback; the context variable is not correctley populated this `context.user` might be undefined, navigating through another route then back to this target route seems to work. If I find how I can safely access it, I'll edit my comment.

Thanks again @zach-betz-hln for your help, you saved me a lot of headache :ok_hand: !

**Comment by zach-betz-hln** [comment]
@tarkant - glad to hear about the progress.

Since the context is populated like this:

```
function InnerApp() {
  const auth = useAuth()
  return <RouterProvider router={router} context={{ auth }} />
}
```

You could try accessing it later like `context?.auth?.user`

**Comment by zach-betz-hln** [comment]
Friendly bump @Smoodi - have you tried the snippets by @tarkant ?

**Comment by Smoodi** [comment]
Hi! Sorry for the slow reply!
I had taken a day off!
Yep, using the Router Context does work!
Thank you a lot for the help!
