### ISSUE TITLE
Missing authentication in direct grant flow

### ISSUE THREAD

**Issue by KjellOlav** [authts/react-oidc-context#1389]
We have a company internal web app with 10 users. I can log in a user using the REST API but I am unable to get the authentication in the auth object. What I do is:
1. Using the Keycloak client credentials I get an access token
2. Using the token I can get a list of the users from Keycloak through the REST API
3. I can select a user, type the password, and using direct grant flow I am able to get an access token for that user

But at this point nothing has happened with the auth object which I get from the useAuth hook.
I read in a post that one should call signin.Redirect to initiate the flow. Is this correct?
I think I am missing something here. Is it possible to get the authenticated user through the useAuth hook if I use Direct grant? How?

**Comment by pamapa** [comment]
To start the process you need to call something like this:
```ts
await auth.clearStaleState();
await auth.signinRedirect();
```

For the supported grants see the README of the underlying library: https://github.com/authts/oidc-client-ts

**Comment by KjellOlav** [comment]
Thank you! I will give it a try.
