### ISSUE TITLE
Is it possible to renew token without hooks?

### ISSUE THREAD

**Issue by MrMamen** [authts/react-oidc-context#1413]
What I want to do is something like this:
```
export const generateHeaders = async () => {
  await doTokenRefresh();
  const user = getUser();
  const token = user?.access_token;
  const headers = new Headers();
  headers.set('Authorization', `Bearer ${token}`);
  return { headers };
};
``

Is it possible to implement doTokenRefresh()?

Since it is not a react component, useAuth is not legal.

**Comment by MrMamen** [comment]
> Hi @MrMamen - would UserManager's [signinSilent](https://authts.github.io/oidc-client-ts/classes/UserManager.html#signinSilent) work here? 

Probably, but how can I get UserManager in a function?

**Comment by zach-betz-hln** [comment]
If you're using this react-oidc-context lib, then `AuthProvider` accepts a `userManager` prop, so whatever you passed there?

Examples: [init of userManager](https://github.com/authts/sample-keycloak-react-oidc-context/blob/9f4f767e5243103bc748b6199ceddf60c875f5b6/react/src/config.ts#L4) and [passing of userManager](https://github.com/authts/sample-keycloak-react-oidc-context/blob/9f4f767e5243103bc748b6199ceddf60c875f5b6/react/src/main.tsx#L15)

**Comment by MrMamen** [comment]
> If you're using this react-oidc-context lib, then `AuthProvider` accepts a `userManager` prop, so whatever you passed there?
> 
> Examples: [init of userManager](https://github.com/authts/sample-keycloak-react-oidc-context/blob/9f4f767e5243103bc748b6199ceddf60c875f5b6/react/src/config.ts#L4) and [passing of userManager](https://github.com/authts/sample-keycloak-react-oidc-context/blob/9f4f767e5243103bc748b6199ceddf60c875f5b6/react/src/main.tsx#L15)

Yes, but the question if it is possible to refresh the token when it is **not** a child of AuthProvider (e.g. redux slice).

**Comment by dantheother** [comment]
@MrMamen if you pass a userManager into `AuthProvider`, you can use that same `UserManager` instance elsewhere, even if you're not a child of the `AuthProvider`. It's the same `UserManager` with the same methods and state.

Using the example from @zach-betz-hln , your generateHeaders could be

```
import { userManager } from './path-to/config';

export const generateHeaders = async () => {
  // await doTokenRefresh(); 
  const user = await userManager,getUser();
  const token = user?.access_token;
  const headers = new Headers();
  headers.set('Authorization', `Bearer ${token}`);
  return { headers };
};
```

I don't know what you had planned for `doTokenRefresh` - `signinSilent` maybe? But the principle holds - if you declare and export your `UserManager` object as a constant and pass it to `AuthProvider`, you can get to the same `UserManager` from anywhere in your code.
