### ISSUE TITLE
How do I access state.data on signinCallback.

### ISSUE THREAD

**Issue by programm-ingovals** [authts/react-oidc-context#155]
If I want to put the url being accessed in state while the user is being sent to the OIDC provider I think I could do this.

```
      auth.signinRedirect({
        state: '/some/relative/url',
      })
```

I can see this is stored as `data` under the stateStorage. But when the Callback comes back I can't seem to find a way to intercept it. The `onSigninCallback` only gets the User object. What am I missing.

**Comment by pamapa** [comment]
This state will be part of the User you get when all is done.
See here: https://authts.github.io/oidc-client-ts/classes/User.html#state

**Comment by programm-ingovals** [comment]
Talk about missing the obvious, thanks.
