### ISSUE TITLE
Add a variable to indicate that a navigator is active

### ISSUE THREAD

**Issue by kherock** [authts/react-oidc-context#173]
I have an app that attempts a silent sign in immediately upon loading. It waits for `isLoading` to become `false` and then issues a silent sign in request if `isAuthenticated` is also false. Within this component, I have state keeping track of this request so that it doesn't duplicate the request on a subsequent rerender.

This works but it gets ugly when I want to make a sign out request elsewhere in the app. Since the component isn't aware that the application initiated a sign out request when the user unloads, the component sees that 1. `isLoading` is still `false` and 2. `isAuthenticated` is also `false` again. Therefore, to stop the silent sign in from running again, I need another variable that lets the component know that it isn't appropriate to initiate a silent sign in despite being unauthenticated.

The simplest solution that works for me would be to set `isLoading: true` while the promise for `signInRedirect`, `signoutRedirect`, etc. are resolving. In addition to this, I could see it also being useful to add another context variable like `activeNavigator: 'redirect' | 'popup' | 'iframe'`. This would allow the application to display more meaningful progress indicators, e.g.

* display an page loading progress bar at the top of the page when `activeNavigator === 'redirect'`
* display a full screen hint to retry the popup flow in case the navigator fails when `activeNavigator === 'popup'`
* show an animated splash screen when `activeNavigator === 'iframe'`

**Comment by pamapa** [comment]
Great idea with `activeNavigator`
For the `isLoading` it means that code like this will trigger for the initial user load and during the login phase, which should be ok.
```
    if (!translationReady || auth.isLoading) {
        return <CircularProgress />;
    }
```
