### ISSUE TITLE
User logout at the end of the session

### ISSUE THREAD

**Issue by ncarlier** [authts/react-oidc-context#239]
Hi,

when activating [monitorSession](https://authts.github.io/oidc-client-ts/interfaces/UserManagerSettings.html#monitorSession) on `UserManagerSettings` an iframe is created to check the session and trigger events if the session is closed (it's the [OIDC Session Management](https://openid.net/specs/openid-connect-session-1_0.html)). The `AuthProvider` hides the `UserManager` instance and therefore the [events](https://authts.github.io/oidc-client-ts/classes/UserManagerEvents.html).
It would be great to provide access to these events or to implement `addUserSignedOut` in order to enable Single Logout. 

```js
userManager.events.addUserSignedOut(async () => {
  console.log('OP session close: user signed out...')
  userManager.signoutRedirect()
})
```

**Comment by pamapa** [comment]
The initial idea was to hide the events, such that we all have the same implementation details. I am not using the `monitorSession` feature, but i think adding that code makes sense and should not harm other usecases.

@kherock What do you think?

**Comment by kherock** [comment]
I don't see any harm in exposing events. I was actually considering deprecating the `onSigninCallback`, `onRemoveUser`, `onSignoutRedirect`, and `onSignoutPopup` props for the 2.0 release since you can replace all of them with a combination of the `activeNavigator` value and event listeners.

**Comment by pamapa** [comment]
We can do so, makes sense, allows more yet unknown use cases.

**Comment by pamapa** [comment]
@ncarlier as a temporary workaround you can create the `UserManager` outside and pass it with the prop `implementation` to the context: https://github.com/authts/react-oidc-context/blob/8f7fc67a63d9943b8cffa0cd0035965d45b75013/src/AuthProvider.tsx#L73

**Comment by ncarlier** [comment]
@pamapa I don't understand how to do this because `implementation` expect a type and not a class instance?

**Comment by pamapa** [comment]
@ncarlier You are right, sorry for the non working idea...
