### ISSUE TITLE
How to handle error during signInSilent?

### ISSUE THREAD

**Issue by warheat1990** [authts/react-oidc-context#259]
I have this code

```
useEffect(() => {
    if (!auth.isAuthenticated && acr) {
      const config: UserManagerSettings = {
        authority: "https://test.com/identity",
        ...
        acr_values: acr
      };
  
      auth.signinSilent(config);
    }
  }, [auth.isAuthenticated])
```

If error is thrown by Identity Server, for example I'm getting `Uncaught (in promise) ErrorResponse: login_required`. I want to be able to handle this and log the user out so the user will need to re-authenticate. How do I achieve this?

**Comment by pamapa** [comment]
- you are using the config not correctly, you must pass it to AuthProvider: `<AuthProvider {...config}>...`.
- calling `auth.signinSilent` is not correct, sign in silent is handled by this library, after you are signed in successfully and the access token has expired. The error you get is correct and expected `ErrorResponse: login_required`
- you want to use `auth.signinRedirect` to sign in
- in case of an error during the auth process there is an error object in auth. You can access it via `auth.error`

Please have a look at the [documentation](https://github.com/authts/react-oidc-context#getting-started)

**Comment by pamapa** [comment]
Hope you made it work, i will soon close this issue.
