### ISSUE TITLE
Unable to change redirect_uri after provider has mounted

### ISSUE THREAD

**Issue by TomCaserta** [authts/react-oidc-context#276]
Effectively I have a component with logic similar to:

```typescript
const MyComponent = () => {
     // Hook that changes with every single page move returning the current URL 
     const path = useBrowserPath();

     const oidcConfig = {
         // ...
         redirect_uri: path,
     }

      return <AuthProvider {...oidcConfig}>
              <App />
       </AuthProvider>;
}
```

The problem is that changing any of the configuration does not cause the auth provider to update the settings nor does it reconstruct the user manager. 

As my goal here is to just update the redirect uri periodically I did also try to set the `useAuth().settings.redirect_uri` etc but since the OidcClient has its own copy of the settings it does not change the redirect_uri it uses.

I believe this is a bug as it should be possible to change this configuration, however please do let me know if theres something fundamentally incorrect with attempting to change the settings/redirect_uri.

**Comment by pamapa** [comment]
Typically the `redirect_url` must be registered in the auth server configuration, as it is security depended. There is no need to change the `redirect_url` dynamically, as this library intercepts the query parameters dealing with the auth process. You must just ensure the configured `redirect_url` points some where into your SPA application. You do **not*" need to setup that route!
e.g. `http://localhost:5000/signin-callback` is a good candidate for development.

**Comment by pamapa** [comment]
will close the issue soon, unless you comment...

**Comment by pamapa** [comment]
if you need to deal with different environments (development vs production), best way is to compile the application code separately per  environment by using something like this in package.json:
```
...
  "scripts": {
        "start": "env-cmd -f .env.development react-scripts start",
        "build": "env-cmd -f .env.development react-scripts build",
        "build:production": "env-cmd -f .env.production react-scripts build",
        ...
  }
...
```

.env.development:
```
REACT_APP_OIDC_AUTHORITY=https://my-auth.com
REACT_APP_OIDC_CLIENT_ID=12345
REACT_APP_OIDC_REDIRECT_URI=http://localhost:5000/signin-callback
```
