### ISSUE TITLE
Documentation on how to enable `state` parameter

### ISSUE THREAD

**Issue by dinvlad** [authts/react-oidc-context#289]
Hi Team,

We're trying to determine if `state` OAuth2 parameter can be auto-generated and verified by this library, or if this is something that the client should implement on their own. Do you have any clarifying documentation on it?

Thank you

**Comment by pamapa** [comment]
The query `state` parameter is handled, needed and by auto-generated the underlying `oidc-client-ts` library. There is a `state` property in the interface and later stored in the user. See e.g. [here](https://github.com/authts/oidc-client-ts/blob/8f1742b3d54c63ed8b9b2b4ab19990e954eb7bc4/src/OidcClient.ts#L27). The second one can be used to round-trip custom data if needed.

**Comment by pamapa** [comment]
I assume you are using v2.1.0...

**Comment by dinvlad** [comment]
Thanks for these instructions! We'll double-check on our end and let you know.
