### ISSUE TITLE
`activeNavigator` is always `undefined`

### ISSUE THREAD

**Issue by fritterhoff** [authts/react-oidc-context#301]
I'm currently trying to utilize this lib in a new React project. So far it works great. The only thing I did not manage to use is the `activeNavigator` property. 

Regardless where I put it and what I try to do, it is always `undefined`. Is there maybe a small hint how I can catch the `signinSilent`?

Maybe I should explain my problem a little bit more in detail. I want to redirect the user to a react route after login, so I created a Route in the BrowserRouter matching to the callback. In consequence this gets also triggered in case of the silent signIn. I want to avoid this 😉

**Comment by pamapa** [comment]
I would expect `activeNavigator` most of the time undefined, unless an navigator (e.g. signin) is currently actively running. See handling of the property [here](https://github.com/authts/react-oidc-context/blob/main/src/AuthProvider.tsx#L137-L142) and [here](https://github.com/authts/react-oidc-context/blob/main/src/reducer.ts#L32-L44).

**Comment by fritterhoff** [comment]
Great thanks for the support!
