### ISSUE TITLE
Allow access to the underlying UserManager instance

### ISSUE THREAD

**Issue by ChillyBots** [authts/react-oidc-context#331]
Thanks for the great work!

Currently, you don't surface the entire UserManager object which has access to callbacks and methods unavailable from anywhere else such as:

```
signoutRedirectCallback
signoutPopupCallback
querySessionStatus
```

Ideally, you could just surface the UserManager alongside the User instance

**Comment by pamapa** [comment]
We are planing to allow to inject an `UserManager` instance, that would help you too. See [this comment](https://github.com/authts/react-oidc-context/issues/313#issuecomment-1087804261).

**Comment by pamapa** [comment]
The `xCallback` functions are handled within this library and are one of the main purpose of this library. There is no need to call them differently. The `querySessionStatus` function is in fact accessible already.

**Comment by rahul-sharma-uipath** [comment]
+1 on this - we have a similar case where we want to get a static copy of the userManager in order to be able to use the `access_token` from static functions

**Comment by pamapa** [comment]
I added a separate issue for passing an UserManager into: #490
