### ISSUE TITLE
authentication upon loading(no login button)

### ISSUE THREAD

**Issue by sanakanchha** [authts/react-oidc-context#355]
First of all, thanks for this great library. I have a SPA that requires the users to authenticate upon loading without having to click on the login button. Is there a way to achieve this? My code pretty much looks similar to the example shared.

index.tsx
************
const oidcConfig = {
	authority: "",
	client_id: "",
	redirect_uri: ""
}

ReactDOM.render(
	<React.StrictMode>
		<AuthProvider {...oidcConfig}>
			<App />
		</AuthProvider>
	</React.StrictMode>,
	document.getElementById('root')
);

Thanks for your help.

**Comment by pamapa** [comment]
With `auth.isAuthenticated` you can check if already authenticated. With auth.signinRedirect() you can sign-in. A combination with React.useEffect might do the trick for you...
