### ISSUE TITLE
oidcStorage does not get any value i'm using it in right way?

### ISSUE THREAD

**Issue by mostafa-zaied** [authts/react-oidc-context#381]
"react-oidc-context": "^2.1.0",
"oidc-client-ts": "^2.0.4",
```
  const oidcConfig = {
    authority: `${process.env.OIDC_AUTHORITY}`,
    client_id: `${process.env.OIDC_CLIENT_ID}`,
    redirect_uri: props.location.origin,
    metadataUrl: `${process.env.OIDC_METADATA_URL}`
  };
```
```
import { User } from "oidc-client-ts"

function getUser() {
  const oidcStorage =  localStorage.getItem(
    `oidc.user:${process.env.OIDC_AUTHORITY}:${process.env.OIDC_CLIENT_ID}`
  );
  if (!oidcStorage) {
    return null;
  }

  return User.fromStorageString(oidcStorage);
}
```
The `useAuth` Working Perfect 👌

**Comment by mostafa-zaied** [comment]
I already get the `oidcStorage` but when passing it to -> `User.fromStorageString(oidcStorage)`  then the object of `User` returned empty i don't know why?  
 I just need this `token` to pass it to ` headers["Authorization"] = `Bearer ${token}`;` so i can use `oidcStorage` directly Right?

**Comment by pamapa** [comment]
maybe your problem is localStorage vs sessionStorage, ensure the seetings are matching with your assumption. Also you can look into both via the browser dev tool...

**Comment by mostafa-zaied** [comment]
I wasted my day thinking that we must use it through the localStorage ,every thing working well now from sessionStorage Thanks @pamapa  💯 💯
