### ISSUE TITLE
ensure React.StrictMode is working

### ISSUE THREAD

**Issue by pamapa** [authts/react-oidc-context#401]

**Comment by philjones88** [comment]
It seems to work for us too but if you have silent renew on it breaks when it does a renew

**Comment by pamapa** [comment]
The silent renew works here fine too:
```
...
[SilentRenewService] _tokenExpiring: silent token renewal successful
```

To reduce the refresh time for testing i use this addition in my settings `accessTokenExpiringNotificationTimeInSeconds: MY_ACCESS_TOKEN_EXPIRE_TIME - 30, // renew every 30s` together with logging support documented [here](https://authts.github.io/oidc-client-ts/#logging).

**Comment by jessydeclerck** [comment]
I noticed the same behaviour, it seems that 

> I am also having an issue if `React.StrictMode` is enabled.
> 
> It can be verified by activating the `React.StrictMode` in the [react-oidc-context example](https://github.com/authts/react-oidc-context/blob/main/example/index.tsx) like this:
> 
> ```tsx
> import React from 'react';
> import ReactDOM from 'react-dom/client';
> import {AuthProvider, AuthProviderProps, useAuth} from 'react-oidc-context';
> 
> const oidcConfig = {
>     authority: 'http://localhost:8081/realms/demo',
>     client_id: 'demo-oidc',
>     redirect_uri: 'http://localhost:3000/auth',
> } as AuthProviderProps;
> 
> function App() {
> 
>     const auth = useAuth();
> 
>     if (auth.isLoading) {
>         return <div>Loading...</div>;
>     }
> 
>     if (auth.error) {
>         return <div>Oops... {auth.error.message}</div>;
>     }
> 
>     if (auth.isAuthenticated) {
>         return (
>             <div>
>                 Hello {auth.user?.profile.sub}{' '}
>                 <button onClick={() => void auth.removeUser()}>
>                     Log out
>                 </button>
>             </div>
>         );
>     }
> 
>     return <button onClick={() => void auth.signinRedirect()}>Log in</button>;
> }
> 
> const root = ReactDOM.createRoot(
>     document.getElementById('root') as HTMLElement
> );
> 
> root.render(
>     <React.StrictMode>
>         <AuthProvider {...oidcConfig}>
>             <App/>
>         </AuthProvider>
>     </React.StrictMode>
> );
> ```
> 
> The login works as expected, but for some reason, an "Oops... No matching state found in storage" error occurs in between.
> 
> This error does not occur, if `React.StrictMode` is not used.

I noticed the same behaviour, it seems that UserManager.signinCallback is called multiple times when React.StrictMode is used. Therefore state is removed from storage and the following signinCallback execution can't find it

**Comment by jessydeclerck** [comment]
Quick workaroud if it can help someone:
`import {UserManager} from "oidc-client-ts";
import {debounce} from "lodash";

class CustomUserManager extends UserManager {
    //override signinCallback, see https://github.com/authts/react-oidc-context/issues/401
    debouncedSigninCallback = debounce((url) => {
        super.signinCallback(url)
    }, 100);

    async signinCallback(url = window.location.href) {
        this.debouncedSigninCallback(url);
    }
}

export default CustomUserManager;`

`<AuthProvider {...oidcConfig} implementation={CustomUserManager}>`

**Comment by pamapa** [comment]
The correct solution to this will look like this as documented [here](https://github.com/reactwg/react-18/discussions/18):

```js
const didInitialise = useRef(false);
...
useEffect(() => {
    if (didInitialise.current) {
      return;
    }
    didInitialise.current = true;
...
```

I guess we need the "return block" per `useEffect`...

**Comment by philjones88** [comment]
@pamapa i think my comment before testing would be that the `useRef` approach logically works for `useEffect` without a cleanup callback? Surely on the "events registering" logic you would end up in a state where the events are removed but `didRegisterForEvents` is still true, due to the cleanup return callback of the `useEffect` ?

**Comment by pamapa** [comment]
good point

**Comment by philjones88** [comment]
@pamapa I think I'm wrong, `useRef` persists through re-renders

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/677167/174754622-de5b05c0-a163-4f9b-8a13-872922256fcb.png">

**Comment by pamapa** [comment]
- I am not 100% sure if we need the guard for the event registering at all
- If we need it, it will be more safe to add this `didRegisterForEvents.current = false;` to the useEffect cleanup function

**Comment by philjones88** [comment]
it does hurt my head but yes. testing it, you'd need to set the `useRef` to `false` in the cleanup. which in my opinion then means there's no point to it.

In StrictMode in development, we'd have to just accept side effects that can be cleaned up safely happening twice.
