### ISSUE TITLE
authorization code with pkce?

### ISSUE THREAD

**Issue by qmffkem** [authts/react-oidc-context#429]
Hello, Thank you for building and maintaining this amazing project.
I've been looking for a way to implement OIDC, especially for one that follows authorization code with PKCE flow, and found this project but I had a hard time to find information about whether it supports the authorization code with PKCE or not...
Is it something I need to implement on top of this project or is it already supported by the project?

Any comments would be appreciated! Thank you!

**Comment by pamapa** [comment]
The authorization code with PKCE flow is supported and besides configuration you do not need to do anything. This library makes use of [oidc-client-ts](https://authts.github.io/oidc-client-ts/), which implements the authz specifics features.

**Comment by pamapa** [comment]
Here https://github.com/authts/oidc-client-ts/blob/main/src/utils/CryptoUtils.ts#L28-L47
