### ISSUE TITLE
Automatically release when PRs are merged

### ISSUE THREAD

**Issue by mariusflorescu** [authts/react-oidc-context#444]
IMO, it would be nice to get the changes released once a PR has been merged to the main branch.

**Comment by pamapa** [comment]
i am staging manually changes and do releases manually, which is fine as is. Do you need a release?

**Comment by mariusflorescu** [comment]
I think that the fix for React 18 is pretty important, thanks!

**Comment by pamapa** [comment]
I will make a release this week!
