### ISSUE TITLE
How to get custom claims included in JWT

### ISSUE THREAD

**Issue by meyerscolton** [authts/react-oidc-context#446]
I am getting a JWT token that includes a custom field in the payload called name. When I view the results of `useAuth()`, stored in a variable called `auth`, I can see the user object which contains the profile object where I would expect the name to be, except the name field is not there. When I decrypt the token stored in auth I can see the name field just fine. Am I supposed to access the name using a different method other than `auth.user.profile.name`?

An example of how the payload is setup is
```
{
    "name": "John Doe",
    ...
}
```

**Comment by dantheother** [comment]
Name is a "well known" oidc claim according to https://github.com/authts/oidc-client-ts/blob/707435fe6c226a3f8a861873a7c27eaa492faa04/src/Claims.ts#L39 - I wonder if that is interfering with things?

Our solution includes a custom tenantGid claim in the identity token (and also the access token) and we're able to retrieve it using _(yes, the as any is nasty, extending the UserProfile object officially is on my TODO list)_

`const tenants = (user?.profile as any)?.tenantGid;`

So I know that this library (probably actually oidc-client-ts) can retrieve custom claims from the identity token and put them on the user profile object.

**Comment by meyerscolton** [comment]
@dantheother thank you for the response. I had been checking the access token this entire time which contained the field, but when I checked the id token I noticed it was missing.

**Comment by djohnsonkc** [comment]
Hi, have there been any updates recently that might address auth.user.profile.name not being present even when name is present in the access_token? Thanks!

**Comment by dantheother** [comment]
@djohnsonkc profile is populated from the identity token, not the access token. Identity token is for use on the client, access token is for use on the server.

**Comment by djohnsonkc** [comment]
Would the user's name be available now somewhere other than in auth.user.profile.name? Thanks.
