### ISSUE TITLE
Getting the  cors policy: no 'access-control-allow-origin' header is present on the requested resource error.

### ISSUE THREAD

**Issue by VijayaSaiRam** [authts/react-oidc-context#460]
Hi team,
I am getting the following error.
access to fetch at '<Authserverurl>/as/token.oauth2' from origin '<domain>' has been blocked by cors policy: no 'access-control-allow-origin' header is present on the requested resource. if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with cors disabled.

Could you please let me know how to solve this issue

**Comment by pamapa** [comment]
You probably need to whitelist your application domain name on your authz server.

**Comment by VijayaSaiRam** [comment]
Thank you for the reply. it is allowed in CORS. working fine

**Comment by Naveenbc** [comment]
Hi @VijayaSaiRam 

I am using IAM and GEMS configuration. I am also getting exactly the same issue. Where do we exactly enable CORS, because I didn't find anything related to CORS in IAM or GEMS. My token URL is also same as yours.
