### ISSUE TITLE
Registration Endpoint? 

### ISSUE THREAD

**Issue by laduke** [authts/react-oidc-context#465]
Hi, 
Thanks for this module. 
Is there a way to get the registration endpoint (from `useAuth()`)? 

I see it on oidc-client-ts https://authts.github.io/oidc-client-ts/interfaces/OidcMetadata.html#registration_endpoint
and in my .well-known/openid-configuration

Can't figure out how to get into OidcMetadata

**Comment by pamapa** [comment]
The userManager has a public function `metadataService`, with this function you get access to the `MetadataService`. However this library does not yet expose this functionally. I would except an MR, if implemented like exposing `events`.

**Comment by laduke** [comment]
Hey, 
Was looking at the linked PR discussion...

Would love a `auth.registerRedirect` method like the `auth.signinRedirect` method. 

Is registration too different to do that way? Would a PR that just did that be acceptable?

**Comment by pamapa** [comment]
> Would love a `auth.registerRedirect` method like the `auth.signinRedirect` method.

This library only exposes what the underlying library `oidc-client-ts` offers. There is no `registerRedirect` function....

**Comment by laduke** [comment]
Closing because I think it's nonsense and a dupe of #331 
Thanks!

**Comment by Mario-Eis** [comment]
We too have this issue. We need access to the token endpoint that is managed in the metadata service that is nor exposed. Is there a proper way now, without working around the libraries design principles?
