### ISSUE TITLE
idle time out for refresh token

### ISSUE THREAD

**Issue by VijayaSaiRam** [authts/react-oidc-context#467]
Hi team,

I idle time out for refresh token is enabled on auth server side. It is said that, if the user is inactive on application for >=30 minutes, the refresh token will be revoked due to idle time out.

But it has been observed that , it is not happening when the application is idle for >=30 minutes, it is not applying , but it is applied when the system is idle for >=30 minutes.

Could you please suggest me . what could be the reason for this behaviour ? do we have any option to enable idle time out timer for  refresh token ?

**Comment by pamapa** [comment]
The underlying library oidc-client-ts is responsible for this. See https://github.com/authts/oidc-client-ts/issues/251
