### ISSUE TITLE
Automatic sign-in

### ISSUE THREAD

**Issue by mindplay-dk** [authts/react-oidc-context#485]
The base example in the README displays a log in button when you launch the app.

This is not how most apps work, and it probably should be updated to something more common.

Most apps will silently and automatically reestablish your previous session, if you close the tab and reopen the app.

I have not been able to achieve that `react-oidc-context` - I only seem to get myself into infinite circular logins.

I'm coming from `oidc-react`, which would automatically take care of this. (but which I have other problems with - namely, silent renewals do not seem to work correctly, which you seem to have given more consideration to.)

~~With this library, it looks like I have to manually call a function like `signinSilent` or `signinRedirect` to make it work?~~

*EDIT:  it turns out `signinRedirect` might *either* redirect or just silently resume a prior session, if possible - just the function name is a little misleading here.*

I'm really missing a better example here, please.

I'm sure others have gotten this to work? It seems the package is very popular, and I doubt everyone is using the example from the README, making their users manually sign in every time they visit the page? 🙂

**Comment by pamapa** [comment]
You can achieve "auto signin" with something like this in your application:

```ts
import { useAuth, hasAuthParams } from "react-oidc-context";
...
{
  const auth = useAuth();
  ...
  useEffect(() => {
    if (!hasAuthParams() && (!user || user.expired)) {
        auth.signinRedirect();
    }
  }, [auth]);
  ...
}
```

Can you test this code, if all good we can add it to the README.md file

**Comment by mindplay-dk** [comment]
I do not see any `hasAuthParams` function in the API?

Here's the approach I came up with, which does appear to work:

```ts
  const { activeNavigator, isLoading, isAuthenticated } = useAuth()

  const autoLogin = !activeNavigator && !isLoading && !isAuthenticated;

  useEffect(() => {
    if (autoLogin) {
      signinRedirect();
    }
  }, [autoLogin])
```

One problem with this, is I cannot get logout to work - it just logs back in immediately. I'm not sure why signing in automatically or silently is even possible after an explicit logout? It probably shouldn't be? If a user explicitly signs out, if we leave the state required to automatically sign back in, they're not really signed out, are they?

This might be an issue with `oidc-client-ts`? Unless it offers some other way to "fully" sign out?

**Comment by mindplay-dk** [comment]
Oh, it's a top level export. 😊

Yes, with your suggested change, logout and redirection now works as well!

Thanks!

It's an open source project - I will post a link to the full working example for future reference.

**Comment by sJJdGG** [comment]
Here's the custom hook I use which covers corner cases I've tried

```tsx
import { hasAuthParams, useAuth } from 'react-oidc-context';

const useAutoLogin = () => {
  const auth = useAuth();

  useEffect(() => {
    if (
      !hasAuthParams() &&
      !auth.isAuthenticated &&
      !auth.activeNavigator &&
      !auth.isLoading
    ) {
      auth.signinRedirect();
    }
  }, [auth]);
};
```

@pamapa Would be happy to let me know if there's any problem with this implementation.

**Comment by pamapa** [comment]
> Would be happy to let me know if there's any problem with this implementation.

looks good, i will take this into the documentation

**Comment by mindplay-dk** [comment]
What I ended up with was [quite a bit simpler](https://github.com/abtion/muffi.net/blob/a04acc8b18a194ef5badbbf47d8487f54f18b011/src/MuffiNet.FrontendReact/ClientApp/src/components/AuthBarrier/index.tsx#L18-L22):

```ts
  useEffect(() => {
    if (!hasAuthParams() && !isAuthenticated) {
      signinRedirect()
    }
  }, [])
```

This seemed to work just fine.

Feel free to study the rest of the solution. I'm not spending more time on it, as I was laid off yesterday. 😅

**Comment by hridaya2004** [comment]
@vejandla @mindplay-dk why not use signinSilent() instead? Won't that work as well?
