### ISSUE TITLE
Apply different configuration values at run-time

### ISSUE THREAD

**Issue by kodeschooler** [authts/react-oidc-context#496]
Using this context, how would one go about changing the acr_values in the settings object after someone is authenticated? For example, when an admin user selects a different customer from a list, I'd like to set the acr_values param in the config object to the tenant selected. It seems that it's designed so you set up the configuration once and that's it. Is there a mechanism for updating any of the settings after UserManager has been set up in the App component?

**Comment by pamapa** [comment]
You made 2 issues for the same. See answer here https://github.com/authts/oidc-client-ts/issues/666
