### ISSUE TITLE
signInSilent and access Signin, SigninSilent and Signout outside the React component.

### ISSUE THREAD

**Issue by vejandla** [authts/react-oidc-context#506]
I've to have both MSAL and React OIDC context in the same code base. 

Based on the host and few other information, I know which IDP I need to use and I wrap my application with MSALProvider or AuthProvider dynamically.

For this reason, I would like to use the signin, signout and refresh methods, with a simple typescript class. So I can bootstrap the respective AuthService based on the authprovider. 

Can you help me to understand on how I can access these methods, outside the React component?

I can't conditionally call useAuth hook as react hooks needs to be at the top level and cannot be inside the if loop.

**Comment by pamapa** [comment]
Maybe MR #466 is what you need, when merged you can pass in a `UserManager` instance....
