### ISSUE TITLE
cant clone the example

### ISSUE THREAD

**Issue by arezookheirabedi** [authts/react-oidc-context#510]
i try to clone your example code but actually i get error in npm install

**Comment by arezookheirabedi** [comment]
@parcel/core: Failed to resolve 'react' from './index.tsx'

  C:\Users\arezoo\Desktop\New folder\react-oidc-context\example\index.tsx:1:24
  > 1 | import * as React from "react";
  >   |                        ^^^^^^^
    2 | import * as ReactDOM from "react-dom";
    3 |

@parcel/resolver-default: Cannot load file '../node_modules/react' in './'.
💡 Did you mean '_./node_modules/react_'?
💡 Did you mean '_./node_modules/@swc_'?

**Comment by pamapa** [comment]
hmm worked here, what is strange:
```
import * as React from "react";
import * as ReactDOM from "react-dom";
```
works?:
```
import React from "react";
import ReactDOM from "react-dom";
```
