### ISSUE TITLE
No Version in react-oidc-context\dist\esm\package.json causes warning.

### ISSUE THREAD

**Issue by BastianTrautmann1992** [authts/react-oidc-context#523]
Directly after installing react-oidc-context and oidc-client-ts I'm getting a warning after npm start.

The warning is: 

Compiled with problems:

WARNING in shared module oidc-client-ts -> C:\Users\btrautmann\workspace\timnet-ui\node_modules\oidc-client-ts\dist\esm\oidc-client-ts.js

No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file C:\Users\btrautmann\workspace\timnet-ui\node_modules\oidc-client-ts\dist\esm\package.json, or manually specify version in shared config.

WARNING in shared module react-oidc-context -> C:\Users\btrautmann\workspace\timnet-ui\node_modules\react-oidc-context\dist\esm\react-oidc-context.js

No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file C:\Users\btrautmann\workspace\timnet-ui\node_modules\react-oidc-context\dist\esm\package.json, or manually specify version in shared config.

Anyone having this as well?

**Comment by pamapa** [comment]
I do not see this warning,
btw in the `node_modules\oidc-client-ts\package.json` we have the version:
```
{
  "name": "react-oidc-context",
  "version": "2.1.1",
...
```

the `node_modules\oidc-client-ts\dist\esm\package.json` is only thought as a type marker

Which version on npm (`npm -v`) do you use? I have 8.11.0

**Comment by BastianTrautmann1992** [comment]
I'm using 8.15.0

**Comment by pamapa** [comment]
That means your is newer. I am happy to accept a merge request to fix this. Is it enough to provide a fake version?

**Comment by BastianTrautmann1992** [comment]
It is completely enough as long the warning is not there anymore :).

**Comment by pamapa** [comment]
Please provide a merge request to fix this...

**Comment by dantaeusb** [comment]
So the reason this is happening is that in the bundled ESM module there's no "version" attribute in `package.json` (only `"type": "module"` there). You can fix that locally in the Federated Plugin by specifying `version` directly (not to be confused with `requiredVersion`, which is about the version range that is requested from the NPM, while `version` is more about the tag with which the module is exposed in the shared modules).
