### ISSUE TITLE
removeUser() doesn't remove session cookie

### ISSUE THREAD

**Issue by flashtheman** [authts/react-oidc-context#524]
The method auth.removeUser() does not end the session completely. When I call auth.signoutRedirect() and confirm the signout, the session cookie in my browser AND the session on my oidc server is completely deleted. However, auth.removeUser() it seems not to destroy the session on the server, and also not delete the cookie in my browser.

Is there a way to signout without redirecting to the signout form?

**Comment by pamapa** [comment]
The `removeUser` only removes the user from the local or session storage. As you note to logout from the server you need `signoutRedirect`. The session cookie is either handled by the autz server or your own application and **not** by this library.
