### ISSUE TITLE
auth provider props and user manager settings have incompatible types

### ISSUE THREAD

**Issue by satanshiro** [authts/react-oidc-context#525]
![image](https://user-images.githubusercontent.com/38865738/192139620-eb3f43a3-8380-4be9-b9b3-7a28e9bb1507.png)
after upgrading there is a mismatch between the 2 types of usersettings and authprovider props because of of the following change
`export declare interface AuthProviderUserManagerProps extends Omit<AuthProviderPropsBase, "redirect_uri" | "client_id" | "authority"> {
    redirect_uri?: never;
    client_id?: never;
    authority?: never;
}`
I'm not quite sure what was the point of this change, would be very happy for an explanataion:) so i can change accordingly.

**Comment by pamapa** [comment]
The idea was to not have both `userManager` and `redirect_uri` + `client_id` + `authority`. In case you use the later one you can use in you application the type `AuthProviderNoUserManagerProps`.

I am not very happy with the current definition of this! The combination type `export type AuthProviderProps = AuthProviderNoUserManagerProps | AuthProviderUserManagerProps;` does not behave as expected: Accept either the first or second definition, but not both...

**Comment by pamapa** [comment]
One alternative could be to just log a warning in case userManager an a userManager settings is provided together. Probably much simpler. Other ideas?

**Comment by pamapa** [comment]
type-wise the modification of the `AuthProviderProps` was a breaking change, sorry about that. I am planing to do a new major release...

**Comment by satanshiro** [comment]
> The idea was to not have both `userManager` and `redirect_uri` + `client_id` + `authority`. In case you use the later one you can use in you application the type `AuthProviderNoUserManagerProps`.
> 
> I am not very happy with the current definition of this! The combination type `export type AuthProviderProps = AuthProviderNoUserManagerProps | AuthProviderUserManagerProps;` does not behave as expected: Accept either the first or second definition, but not both. Any better solution?

I'll have to think of a solution. in general for me it was comfortable that I was able to instantiate usermanager without the context and with the context using the same type depending on how the page loads. as a general sense I think typing should reflect the code behavior as much as possible is there a benefit to enforce you cannot pass the extra params to props?

**Comment by satanshiro** [comment]
> The idea was to not have both `userManager` and `redirect_uri` + `client_id` + `authority`. In case you use the later one you can use in you application the type `AuthProviderNoUserManagerProps`.
> 
> I am not very happy with the current definition of this! The combination type `export type AuthProviderProps = AuthProviderNoUserManagerProps | AuthProviderUserManagerProps;` does not behave as expected: Accept either the first or second definition, but not both. Any better solution?

I'll have to think of a solution. in general for me it was comfortable that I was able to instantiate usermanager without the context and with the context using the same type depending on how the page loads. as a general sense I think typing should reflect the code behavior as much as possible is there a benefit to enforce you cannot pass the extra params to props?

**Comment by pamapa** [comment]
I have improved the current solution in the MR #528.

**Comment by satanshiro** [comment]
I took a look now and it's understandable, thanks have a nice day
