### ISSUE TITLE
revokeTokens is not working

### ISSUE THREAD

**Issue by VladSSO** [authts/react-oidc-context#557]
I'm not an expert in front end programming, just needed to test OIDC PKCE Signin and Signout (token revoking including). I'm calling revokeTokens from the button
 <button onClick={auth.revokeTokens}>
                    RevokeTokens
  </button>
Token types are specified in oidcConfig
revokeTokenTypes:  ["access_token", "refresh_token"]

**Getting an error**

UserManager.ts:542 
        
       Uncaught (in promise) TypeError: types.filter is not a function
    at UserManager._revokeInternal (UserManager.ts:542:1)
    at UserManager.revokeTokens (UserManager.ts:535:1)

Thus is the code of interest
 public async revokeTokens(types?: RevokeTokensTypes): Promise<void> {
        const user = await this._loadUser();
        await this._revokeInternal(user, types);
    }

    protected async _revokeInternal(user: User | null, types = this.settings.revokeTokenTypes): Promise<void> {
        const logger = this._logger.create("_revokeInternal");
        if (!user) return;

        const typesPresent = types.filter(type => typeof user[type] === "string");

When observing in the debug
this.settings.revokeTokenTypes: Array(2)
0:"access_token"
1:"refresh_token"
length:2

types: SyntheticBaseEvent

A default parameter in  _revokeInternal is not used, because SyntheticBaseEvent is passed from revokeTokens.

What am I doing wrong?
Regards

**Comment by pamapa** [comment]
`protected async _revokeInternal(user: User | null, types = this.settings.revokeTokenTypes)`
-> types must be of type string[]

Somehow in your code its type is SyntheticBaseEvent, which can not work.

`Uncaught (in promise) TypeError: types.filter is not a function`: filter is supposed to work an a array here...

**Comment by VladSSO** [comment]
I resolved it by using auth.signoutRedirect() and  revokeTokensOnSignout:  true property
