### ISSUE TITLE
Warning: An update to AuthProvider inside a test was not wrapped in act(...).

### ISSUE THREAD

**Issue by AlbertoSadoc** [authts/react-oidc-context#558]
We have a component that wraps the `AuthProvider` with the settings and the callback functions, and when writing tests for the component we started to see these errors in the console:
![image](https://user-images.githubusercontent.com/6703955/197178343-9ba8172a-eef1-45fd-bbab-318991c757c2.png)

It happens even when writing a simple test like this:
```ts
  it("tests", () => {
    const settings: AuthProviderNoUserManagerProps = {
      authority: "authority",
      client_id: "client_id",
      redirect_uri: "callback",
    };

    render(<AuthProvider {...settings}></AuthProvider>);
  });
```

Cannot find a way to drop that message, does not work by wrapping - [unnecessarily](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#wrapping-things-in-act-unnecessarily) - the `render` in `act()`, or cannot follow any help I found since it (https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning)

React: v18.2.0
Jest: v27.5.1

**Comment by Danielvandervelden** [comment]
I have the exact same problem right now, would really like a solution to this as well.

**Comment by AlbertoSadoc** [comment]
I managed to resolve the issue by creating a promise and awaiting it with an `act`

```ts
  it("tests", async () => {
    const promise = Promise.resolve();
    const settings: AuthProviderNoUserManagerProps = {
      authority: "authority",
      client_id: "client_id",
      redirect_uri: "callback",
    };

    render(<AuthProvider {...settings}></AuthProvider>);

    await act(async () => {
      await promise;
    });
  });
```
