### ISSUE TITLE
How to dynamicaly change oidcConfig?

### ISSUE THREAD

**Issue by VladSSO** [authts/react-oidc-context#567]
I want to let a user to enter oidcConfg parameters into a form before a login is there a way to do it?

**Comment by pamapa** [comment]
The underlying library `oidc-client-ts` is designed to handle the configuration read-only. This library builds on that. You use case is quite different for most others. as such its not supported...

**Comment by karenmnyv** [comment]
It is possible to add some configuration to the signinRedirect() function, such as ui_locales, if that helps
