### ISSUE TITLE
Include redirect_uri query parameter in silent refresh?

### ISSUE THREAD

**Issue by n0rwin** [authts/react-oidc-context#581]
I am trying to use react-oidc-context to login with Azure AD B2C.
The login works as expected, but I cannot get the silent refresh to work.
Before the access token expires, the library sends a request to the auth endpoint including the refresh_token.
But Azure AD B2C also requires that you include the redirect_uri again in the query parameters.
I get the following error response: AADB2C90083: The request is missing required parameter: redirect_uri.

Is there a way I can control, that this parameter gets included in the silent refresh call?
I looked through the documentation and couldn't find a suitable configuration setting, that would take care of that.
I tried setting the extraQueryParams property in the oidcConfig object, but that will lead to the redirect_uri parameter ending up twice in the initial login request and still isn't included in the silent refresh call.

If it is not possible to adapt the silent refresh in that way. What would be my options implementing the token refresh myself?

**Comment by pamapa** [comment]
See SigninSilentArgs in UserManager:
https://github.com/authts/oidc-client-ts/blob/2e49894fa76681fbab63ee3cd1f7ef094eea4fa2/src/UserManager.ts#L47


`signinSilent({redirect_url: "123"})`

**Comment by n0rwin** [comment]
Thank you. If I understand your response correctly, that means, that I have to call signinSilent myself, passing the redirect_url as parameter in the SigninSilentArgs object.
So I guess there is no way, react-oidc-context passes this parameter on its own when just configuring automaticSilentRenew = true?
That would mean that I have to implement my own refresh mechanism, either time based, or by reacting to failed calls where the token has expired. Correct?

**Comment by pamapa** [comment]
> That would mean that I have to implement my own refresh mechanism, either time based, or by reacting to failed calls where the token has expired. Correct?

Yes, that was my idea, i just looked at the oidc-client-ts code, but your code path the args parameter is not taken into account yet, as such that will also not work yet:
```js
public async signinSilent(args: SigninSilentArgs = {}): Promise<User | null> {
        const logger = this._logger.create("signinSilent");
        const {
            silentRequestTimeoutInSeconds,
            ...requestArgs
        } = args;
        // first determine if we have a refresh token, or need to use iframe
        let user = await this._loadUser();
        if (user?.refresh_token) {
            logger.debug("using refresh token");
            const state = new RefreshState(user as Required<User>);
            return await this._useRefreshToken(state);
        }
```

You would need to provide a merge request in oidc-client-ts to add this feature.
1. allow to pass args also into `RefreshState` and make use of it

I am not using the "the Refresh Token grant type".
Somehow i do not understand why a `redirect_uri` for the Refresh Token grant type. As this is a http post request and the direct response contains all information.  Can you search in the official "Azure AD B2C" documentation for  Refresh Token grant type.
aka `grant_type = "refresh_token"`
