### ISSUE TITLE
How to redirect user to current page 

### ISSUE THREAD

**Issue by adibamine** [authts/react-oidc-context#590]
Is it possible to set the redirect uri to the current url from witch the user is authenticating?
For exemple, If a user is in page X and decide to connect/subscribe, it would be better if he is redirected back to page X rather that the homepage or whatever url is configured.

Current config:
const oidcConfig = {
  authority: "YYY",
  client_id: "XX",
  redirect_uri: "http://localhost:3000",
  onSigninCallback: (): void => {
    window.history.replaceState({}, document.title, window.location.pathname);
    }
};

**Comment by adibamine** [comment]
I ended up using the signinRedirect state. I'm not sure if it's the best solution.
1 -auth.signinRedirect({state:window.location.href})

2- onSigninCallback: (user): void => {
    window.history.replaceState({}, document.title, window.location.pathname);
    window.location = user.state || "/";
    }

**Comment by dantheother** [comment]
I don't know if this is **the** way to do it, but it sure looks good. In my code I've been tucking something away in `sessionStorage`, then retrieving it in the `onSigninCallback`, but I think I like this state approach better.

One thing I'd suggest though is to store the relative path (`window.location.pathName` and `search` if you need it), not the full url. And also cleanse the state parameter when you come back, make sure it's "acceptible". That'll stop bad actors from hijacking the state parameter to get redirected to an external website upon successful auth. I don't know what the attack vector would be there, but it _feels_ like one.

**Comment by axelboc** [comment]
Could this also be achieved with the `state` option?

```js
const { pathname, search, hash } = globalThis.location;

auth.signinRedirect({
  state: JSON.stringify({ returnTo: { pathname, search, hash } });
});
```

```js
onSigninCallback={(user) => {
  if (user) {
    const returnTo = JSON.parse(user.state).returnTo;
    // ...
  }
}}
```
