### ISSUE TITLE
session issue in nextjs app(ssr)

### ISSUE THREAD

**Issue by adibamine** [authts/react-oidc-context#607]
I have two applications, one using react js(spa) and another one using nextjs(ssr).
i have integrated keycloak successfuly in both apps, however i´ve noticed that in the nextjs app, the user session is lost between tabs, i mean that if i login and then opened a new tab in the same navigator, i won t be connected in the new one. I guess that s caused by the userStore which is localstorage by default, maybe it needs to use cookies instead in ssr case.

Is there a workaround for this?
Thank you

**Comment by Achill113** [comment]
@adibamine did you find a solution for this? I'm running into similar with React, opening any link in my application in a new tab loses the session and goes through the authentication process again.
