### ISSUE TITLE
Adding signoutSilent

### ISSUE THREAD

**Issue by karenmnyv** [authts/react-oidc-context#613]
I'm currently working on a project where we need some kind of silent sign out. Would it be possible to add `signoutSilent` from [oidc-client-ts](https://authts.github.io/oidc-client-ts/classes/UserManager.html#signoutSilent)?

**Comment by pamapa** [comment]
Have you tried `signoutRedirect`?

**Comment by pamapa** [comment]
I assume you have such a function already written by yourself. Can you share the code here. If it follows the spec we can merge it...

**Comment by karenmnyv** [comment]
I'm not sure I understand, but are you assuming I already have an implementation of `signoutSilent`? Unfortunately I don't, I was kind of hoping it would be possible to add the one from [oidc-client-ts](https://authts.github.io/oidc-client-ts/classes/UserManager.html#signoutSilent), since react-oidc-context already is based on it. 
I could be wrong though, I'm a bit new to all of this.

Their implementation of it is here: https://github.com/authts/oidc-client-ts/blob/c6b44cfed9e12eeff42d6dc99e59cf5f4fd00bf0/src/UserManager.ts#L580

**Comment by pamapa** [comment]
Ah, now i understand you :-) Sorry for the confusion. Yes we can support here. Can you provide a MR doing so?. You can follow the implementation of `signoutRedirect`: extend `navigatorKeys`, `const signoutSilent = useCallback(...` and `AuthContext.Provider`. Plus a unit-test might be useful too...

**Comment by karenmnyv** [comment]
Yes, I'll do it at the first opportunity :D

**Comment by jgregory-apogee** [comment]
Hope I'm not stepping on any toes, but we needed this, too, so I went ahead and opened a PR for it.  I'm more or less piggy-backing on the implementations for `signoutRedirect` and `signoutPopup`
