### ISSUE TITLE
TypeScript "Could not find a declaration file" error when `tsconfig.moduleResolution` is "Node16" or "NodeNext"

### ISSUE THREAD

**Issue by jrgermain** [authts/react-oidc-context#620]
I have a project that uses `react-oidc-context`. When I set `moduleResolution` in the project's `tsconfig.json` to `"Node16"` (or `"NodeNext"`), TypeScript throws an error saying that it cannot find `react-oidc-context`'s declaration file. This error does not occur when `moduleResolution` is set to `"Node"`.

This is how I am importing the library:

```ts
import { useAuth } from "react-oidc-context";
```

This is my tsconfig (I am using TypeScript and Vite):

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node16",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "importsNotUsedAsValues": "error"
  },
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

And this is the error message I get:

```
Could not find a declaration file for module 'react-oidc-context'. '[redacted]/node_modules/react-oidc-context/dist/esm/react-oidc-context.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-oidc-context` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-oidc-context';`ts(7016)
```

We should be able to fix this issue and support both types of module resolution by changing the format of the `export` key in `react-oidc-context`'s `package.json`.

This is the current format being used by `react-oidc-context`:
```json
  "exports": {
    ".": {
      "import": "./dist/esm/react-oidc-context.js",
```

Changing it to this fixes the issue:
```json
  "exports": {
    ".": {
      "import": {
        "types": "./dist/types/react-oidc-context.d.ts",
        "default": "./dist/esm/react-oidc-context.js",
      },
```

**Comment by jrgermain** [comment]
For reference, this seems to affect a lot of libraries. [This comment about this issue on `@vitejs/plugin-vue`](https://github.com/vitejs/vite/issues/10481#issuecomment-1280335703) was especially helpful for my understanding.

**Comment by pamapa** [comment]
Does this work too? This is similar than what we have in odic-client-ts:

```
"exports": {
    ".": {
      "types": "./dist/types/react-oidc-context.d.ts",
      "import": "./dist/esm/react-oidc-context.js",
      "require": "./dist/umd/react-oidc-context.js"
    },
    "./package.json": "./package.json"
  },
```

**Comment by pamapa** [comment]
Please create a merge request.
