### ISSUE TITLE
How to enable debug Logging properly?

### ISSUE THREAD

**Issue by fl0wx** [authts/react-oidc-context#634]
Hey all,
i tried to enable Logging, and it kind of worked but dont log any debug messages. Can you help me please? I did this:
![image](https://user-images.githubusercontent.com/2448081/213464773-ab9f4409-1fa2-409a-9082-bc3b495011f6.png)
and also tried to set the level & Logger outside of the hook. I only see one info message in my browser alongside with a few errors but not a single debug message (there should have been many, based on what i have seen in the code):
![image](https://user-images.githubusercontent.com/2448081/213465136-8665b231-1d67-43ab-80c2-d78f7d111562.png)
Can you please provide support here?
Thanks and regards

**Comment by pamapa** [comment]
The logging setup looks good. The logger and level is hold globally:
```
Log.setLogger(console);
Log.setLevel(Log.DEBUG);
```

Are you some where initiating the authentication (e.g. `auth.signinRedirect()`), if not you will not see logs...

**Comment by fl0wx** [comment]
Yes @pamapa , like you can see here:
`import {hasAuthParams, useAuth} from "react-oidc-context";
import * as React from "react";

export default function OidcPoC() {
    const auth = useAuth();

    // automatically sign-in
    React.useEffect(() => {
        if (!hasAuthParams() &&
            !auth.isAuthenticated && !auth.activeNavigator && !auth.isLoading) {
            auth.signinRedirect();
        }
    }, [auth.isAuthenticated, auth.activeNavigator, auth.isLoading, auth.signinRedirect]);
    
    if (auth.activeNavigator) {
        return <div>Signing you in/out...</div>;
    }
    if (auth.error) {
        return <div>Oops... {auth.error.message}</div>;
    }
    if (!auth.isAuthenticated) {
        return <div>Unable to log in</div>;
    }
    console.log(auth.user)

    return <>
        <button onClick={() => void auth.removeUser()}>Log out</button>
        </>;
}`

if i set loadUserInfo to false, the login is working correctly but if i set it to true, i get 403 & cors errors and im unable to debug since i get no debug logs

**Comment by pamapa** [comment]
- To find out why you have no logging, use the debugger...maybe adding the `debugger;` instruction in your code helps you.
- To get ride of the cors error you may need to whitelist your hostname on the authz side...

**Comment by pamapa** [comment]
You could enable the logger like, to be 100% sure its ok:
```js
function getOidcConfig(enableLogger = false): AuthProviderNoUserManagerProps {
  if (enableLogger) {
    // setup oidc logger
    Log.setLogger(console);
    Log.setLevel(Log.DEBUG);
  }
  return {
    authority = ...        
  }
}
const oidcConfig = getOidcConfig(true);
...
```

**Comment by fl0wx** [comment]
okay thanks and where should i call this ?

> You could enable the logger like, to be 100% sure its ok:
> 
> ```js
> function getOidcConfig(enableLogger = false): AuthProviderNoUserManagerProps {
>   if (enableLogger) {
>     // setup oidc logger
>     Log.setLogger(console);
>     Log.setLevel(Log.DEBUG);
>   }
>   return {
>     authority = ...        
>   }
> }
> const oidcConfig = getOidcConfig(true);
> ...
> ```

**Comment by fl0wx** [comment]
> * To find out why you have no logging, use the debugger...maybe adding the `debugger;` instruction in your code helps you.
ill try this thanks
> * To get ride of the cors error you may need to whitelist your hostname on the authz side...
i cannot change anything on authz server side (authn and authz is the same server, and authn works). if the client sends an origin header, then everything should work. The other requests (openid config & get auth token etc) work without any issue.

**Comment by fl0wx** [comment]
> You could enable the logger like, to be 100% sure its ok:
> 
> ```js
> function getOidcConfig(enableLogger = false): AuthProviderNoUserManagerProps {
>   if (enableLogger) {
>     // setup oidc logger
>     Log.setLogger(console);
>     Log.setLevel(Log.DEBUG);
>   }
>   return {
>     authority = ...        
>   }
> }
> const oidcConfig = getOidcConfig(true);
> ...
> ```

doenst work (same as before): 
![image](https://user-images.githubusercontent.com/2448081/213718669-3d2adbcf-c935-475b-8f1e-8a99f55df109.png)

**Comment by pamapa** [comment]
Have you somewhere else overwritten console.debug or console.trace?

**Comment by fl0wx** [comment]
> Have you somewhere else overwritten console.debug or console.trace?

hey @pamapa, im not aware that i have anything else overwritten (its an pretty small test app so there is no hidden code or sth). Also if i debug the code, the code passes the log debug part but the text doesnt appear on console output:
![image](https://user-images.githubusercontent.com/2448081/214575166-bcd30aac-6fe4-4145-8ab5-0117adc85940.png)
![image](https://user-images.githubusercontent.com/2448081/214575180-db1792b4-54c4-43cb-96b4-4b7435b54f24.png)

**Comment by pamapa** [comment]
Ensure to enable Verbose (not default) in e.g. Chrome console
![image](https://user-images.githubusercontent.com/10164638/214592777-f4cefb8e-be22-42e5-859d-ec9ca3c4bd32.png)

**Comment by fl0wx** [comment]
> Ensure to enable Verbose (not default) in e.g. Chrome console ![image](https://user-images.githubusercontent.com/10164638/214592777-f4cefb8e-be22-42e5-859d-ec9ca3c4bd32.png)

uff thanks a lot, now its working :D didnt knew that, so thanks a lot. maybe you should add a hint in the docs to enable that :)
