### ISSUE TITLE
CORS error on sign in

### ISSUE THREAD

**Issue by lmyslinski** [authts/react-oidc-context#654]
I'm trying to use Jumpcloud as OIDC provider - I get a cors error when trying to sign in:

I've seen https://github.com/authts/react-oidc-context/issues/460, however, Jumpcloud does not provide an option to set a whitelisted domain. On top of that, I'm not sure if that's a problem on their end. Here's the error from the console:

```
Access to fetch at 'https://oauth.id.jumpcloud.com/.well-known/openid-configuration' from origin 'https://myapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

However, when I look at the actual response, I don't see that header:

![Zrzut ekranu 2023-02-3 o 17 58 14](https://user-images.githubusercontent.com/5132069/216662337-c6c7343d-3d05-4723-8677-28d4c13ae2aa.png)

Source code:

```
const SignIn = () => {
  const auth = useAuth();
  const router = useRouter();

  const loginViaSSO = async () => {
    console.log(`Redirecting to SSO`)
    console.log(JSON.stringify(auth.settings))
    await auth.signinRedirect()
  }

  if (auth.isLoading) {
    return <div>Loading...</div>;
  }

  if (auth.error) {
    return <div>Oops... {auth.error.message}</div>;
  }

  if (auth.isAuthenticated) {
    console.log(`Pushing to /`)
    router.push("/")
  }
  
  return (
    <>
      <AuthLayout>
        <div className="flex w-1/4 flex-col space-y-4 divide-gray-400 divide-y">
          <div className="flex flex-col space-y-4 pt-8 items-center justify-center">
            <button onClick={() => loginViaSSO()} className="w-full rounded bg-indigo-400 py-4 px-4 text-lg">
              Continue with SSO
            </button>
          </div>
        </div>
      </AuthLayout>
    </>
  );
```

I can successfully fetch `https://oauth.id.jumpcloud.com/.well-known/openid-configuration` from any other client, so perhaps `no-cors` should be set within the client?

**Comment by lmyslinski** [comment]
Ok, I've figured this out via https://authts.github.io/oidc-client-ts/#usermanager but that was not an easy find:
```
  const oidcConfig: OidcClientSettings = {
    authority: "https://oauth.id.jumpcloud.com/",
    client_id: "b04e9bc0-2f43-4777-9bd6-ddf8636e7ac5",
    redirect_uri: "https://myapp.com/",
    response_type: "code",
    metadata: {
      authorization_endpoint: "https://oauth.id.jumpcloud.com/oauth2/auth",
      issuer: "https://oauth.id.jumpcloud.com/",
      userinfo_endpoint: "https://oauth.id.jumpcloud.com/userinfo",
      end_session_endpoint: "https://oauth.id.jumpcloud.com/oauth2/sessions/logout"
    }
  };
```

It would be great to have this doc in the library readme

**Comment by pamapa** [comment]
Adding `{ mode: 'no-cors'})` to fetch is not a good idea, see here https://stackoverflow.com/questions/43262121/trying-to-use-fetch-and-pass-in-mode-no-cors

Have you added your host in the allow list of the authz server?

**Comment by pamapa** [comment]
> It would be great to have this doc in the library readme

Here would be a nice place: https://github.com/authts/oidc-client-ts/blob/main/docs/index.md#provider-specific-settings

**Comment by dreyes84** [comment]
Hello I have an issue with cors but a little different I have provide the necessary  metadata 
    issuer: ".../services/trust",
    authorization_endpoint: ".../oauth2/authorize/",
    token_endpoint: "../oauth2/token/",
 end_session_endpoint: ".../logout",

and I got blocked by cors, consolo log

Access to fetch at '.../oauth2/token/' from origin 'https://localhost:44348' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
JsonService.ts:51          POST .../oauth2/token/ net::ERR_FAILED 200 (OK)

any idea on how to check?

**Comment by lmyslinski** [comment]
> Hello I have an issue with cors but a little different I have provide the necessary metadata issuer: ".../services/trust", authorization_endpoint: ".../oauth2/authorize/", token_endpoint: "../oauth2/token/", end_session_endpoint: ".../logout", userinfo_endpoint: "../userinfo",
> 
> and I got blocked by cors, consolo log
> 
> Access to fetch at '.../oauth2/token/' from origin 'https://localhost:44348' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. JsonService.ts:51 POST .../oauth2/token/ net::ERR_FAILED 200 (OK)
> 
> any idea on how to check?

If you're still getting the CORS error that means you didn't specify all the metadata endpoints correctly. Manually send a GET request to your provider's endpoint (ex. `https://oauth.id.jumpcloud.com/.well-known/openid-configuration`) and paste the exact endpoints as I have above

**Comment by lmyslinski** [comment]
> Adding `{ mode: 'no-cors'})` to fetch is not a good idea, see here https://stackoverflow.com/questions/43262121/trying-to-use-fetch-and-pass-in-mode-no-cors
> 
> Have you added your host in the allow list of the authz server?

Jumpcloud doesn't provide that option. I've given up on trying to integrate with them, I'll publish that PR with the doc update

**Comment by lmyslinski** [comment]
> > Adding `{ mode: 'no-cors'})` to fetch is not a good idea, see here https://stackoverflow.com/questions/43262121/trying-to-use-fetch-and-pass-in-mode-no-cors
> > Have you added your host in the allow list of the authz server?
> 
> @pamapa Jumpcloud doesn't provide that option. I've given up on trying to integrate with them, I'll publish that PR with the doc update

**Comment by dreyes84** [comment]
> @dreyes84
> 
> > Hello I have an issue with cors but a little different I have provide the necessary metadata issuer: ".../services/trust", authorization_endpoint: ".../oauth2/authorize/", token_endpoint: "../oauth2/token/", end_session_endpoint: ".../logout", userinfo_endpoint: "../userinfo",
> > and I got blocked by cors, consolo log
> > Access to fetch at '.../oauth2/token/' from origin 'https://localhost:44348' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. JsonService.ts:51 POST .../oauth2/token/ net::ERR_FAILED 200 (OK)
> > any idea on how to check?
> 
> If you're still getting the CORS error that means you didn't specify all the metadata endpoints correctly. Manually send a GET request to your provider's endpoint (ex. `https://oauth.id.jumpcloud.com/.well-known/openid-configuration`) and paste the exact endpoints as I have above

hello and thanks for the reply, yes I  did that before raising the issue, also I did try to add the domain auth in the proxy option in the package.json (just for development), we already have some .net applications consuming the adfs in localhost I know is totally different but I'm new to react :p

**Comment by lmyslinski** [comment]
@dreyes84 so what does the full `OidcClientSettings` that you're passing in look like?

**Comment by lmyslinski** [comment]
@pamapa Was about to publish the doc PR but seeing that https://github.com/authts/oidc-client-ts/blob/main/docs/index.md#provider-settings-if-cors-not-supported-on-oidcoauth2-provider-metadata-endpoint is already there with the metadata stuff I think we're good here
