### ISSUE TITLE
Question: When will the new version with silent sign-out be released?

### ISSUE THREAD

**Issue by Kayeeec** [authts/react-oidc-context#669]
Hi, I need the new `oidc-client-ts` silent sign-out feature and I noticed that you've already implemented the support for it (e20285c). Unfortunately, it did not make the 2.2.1 release. 

So when can we expect a new release with this feature? 
Is there anything people like me could help with to speed it up? 

I'm just asking to know if working on a workaround is worth it. It would be a wasted effort if a new release were just around the corner. 

Many thanks for your work, this is a great library!

**Comment by pamapa** [comment]
i will make a release this week for you.

**Comment by Kayeeec** [comment]
Thanks a lot! :+1: 
There's no need to rush or stress out about it, it's totally fine by me if it happens within weeks.
