### ISSUE TITLE
JWT.io gives me "Invalid signature" when using signinSilent

### ISSUE THREAD

**Issue by seanhakbb** [authts/react-oidc-context#684]
I got everything working with Azure AD, `props.auth?.user.id_token` returns a token I can use for API requests.

But when I login user using signinSilent I get a new token that validates to "Invalid signature" in JWT.io.
```
React.useEffect(() => {
		return props.auth?.events.addAccessTokenExpiring(() => {
			if (
				confirm(
					"You're about to be signed out due to inactivity. Press continue to stay signed in."
				)
			) {
				const signing = props.auth?.signinSilent();
				signing?.catch(() => {
					//If silent fails redirect to login page for token renewal.
					props.auth?.signinRedirect();
				});
			}
		});
	}, [props, props.auth?.events, props.auth?.signinSilent]);
```

I'm not sure even where to begin debug, I have no control over Azure AD app, 
my oidc config is pretty basic:
```
oidcConfigEnv = {
			authority: oidcAuthority ?? '',
			client_id: oidcClientId ?? '',
			redirect_uri: oidcRedirectUri ?? '',
			includeIdTokenInSilentRenew: true,
			silent_redirect_uri: oidcRedirectUri ?? '',
		};
```

Please any advice where to continue, or maybe a working example/app?

**Comment by seanhakbb** [comment]
> The jwt token directly comes for the Azure AD. For debugging have a look at enabling logging: https://authts.github.io/oidc-client-ts/#logging

Thanks @pamapa . How do I even access OIDC/setLog method?

**Comment by pamapa** [comment]
setup oidc logger:
```
Log.setLogger(console);
Log.setLevel(Log.DEBUG);
```

-> watch in your browsers dev tool console....
