### ISSUE TITLE
Query parameters are added to the redirect url after login

### ISSUE THREAD

**Issue by MichaelJHaywood** [authts/react-oidc-context#689]
After the user logs in we are having query parameters added onto the redirect URL. E.g. `state`, `session_state` and `code`.

This means if the user refreshes their page they get an error as the query parameters aren't expected.   

I've found a similar issue in a separate library where they seem to have an option to remove the hashes.
https://github.com/manfredsteyer/angular-oauth2-oidc/issues/1071

I've looked through the different options I can pass using the `AuthProvider` but can't find anything on how I can redirect to the specified URL without appending any parameters?

**Comment by dantheother** [comment]
They can be removed in the `onSigninCallback` - the readme mentions this, search for "refresh"

**Comment by MichaelJHaywood** [comment]
I missed that. Thank you!
