### ISSUE TITLE
You must provide an implementation of onSigninCallback to oidcConfig

### ISSUE THREAD

**Issue by rwb196884** [authts/react-oidc-context#698]
What does it mean?

What do I need to do?

This makes no sense
https://github.com/authts/react-oidc-context/blob/f175dcba6ab09871b027d6a2f2224a17712b67c5/src/AuthProvider.tsx#L20-L30
because the interface `AuthProviderProps` contains two things called `onSigninCallback `.

I see that after logging in all of the GET parameters are left in the address bar, and I guess that this has something to do with making them go away?

**Comment by dantheother** [comment]
Yep, that's exactly what you can do with this callback. Another common use is to redirect the user to their original destination, before you sent them off to be authenticated.

Here's a simplified version I have in one of our projects

```
  <AuthProvider
    onSigninCallback={() => {
      const url = window.sessionStorage.getItem(ORIGINAL_DESTINATION)
      if (url) {
        window.sessionStorage.removeItem(ORIGINAL_DESTINATION)
        window.location.replace(url)
      } else {
        window.history.replaceState(
          {},
          document.title,
          window.location.pathname
        )
      }
    }}
  // ... rest of auth props
  >
    {children}
  </AuthProvider>

```
