### ISSUE TITLE
Not signed in if opened in a new tab

### ISSUE THREAD

**Issue by ghoshbishakh** [authts/react-oidc-context#707]
After a successful sign-in, if the app is opened in a new tab, the tab is not signed in.

Are the tokens no saved in localstorage? And what should I do to preserve the state between the tabs?

Thank you, I really appreciate all the hard work in this project.

**Comment by rameshkunwar** [comment]
By default, it's in session storage. Use this code to store in local storage.
`  userStore: new WebStorageStateStore({ store: window.localStorage }),`
