### ISSUE TITLE
[Fixed] Unable to use localStorage with signinRedirect method in Next.js app

### ISSUE THREAD

**Issue by danielmarcano** [authts/react-oidc-context#729]
Hi there, hope you are doing great!

First and foremost, thank you for your contributions to the open source community!

I have encountered a blocker issue regarding the `signinPopup` method from the `useAuth` hook, when passing the popupWindowTarget: '_self' to the AuthProviderProps.

Here's the code:

- src/AuthProvider.tsx

```tsx
import { useEffect, useState } from 'react';
import type { AuthProviderProps } from 'react-oidc-context';
import { AuthProvider as OIDCProvider } from 'react-oidc-context';
import { WebStorageStateStore } from 'oidc-client-ts';

const OIDC_CONFIG: AuthProviderProps = {
  authority: process.env.NEXT_PUBLIC_MICROSOFT_AUTHORITY,
  client_id: process.env.NEXT_PUBLIC_MICROSOFT_CLIENT_ID,
  redirect_uri: process.env.NEXT_PUBLIC_MICROSOFT_REDIRECT_URI,
  popup_redirect_uri: process.env.NEXT_PUBLIC_MICROSOFT_REDIRECT_URI, // http://localhost:3000
  scope: process.env.NEXT_PUBLIC_MICROSOFT_SCOPE,
  post_logout_redirect_uri: process.env.NEXT_PUBLIC_MICROSOFT_REDIRECT_URI, // http://localhost:3000
  response_type: 'code',
  popupWindowTarget: '_self',
};

export function AuthProvider({ children }: AuthProviderProps) {
  const [config, setConfig] = useState<AuthProviderProps>({ ...OIDC_CONFIG });

  const [timestamp, setTimeStamp] = useState(Date.now());

  useEffect(() => {
    setTimeStamp(Date.now());

    setConfig({
      ...OIDC_CONFIG,
      userStore: new WebStorageStateStore({
        store: window.localStorage,
      }),
    });
  }, []);

// We use the timestamp state to re-render entire OIDCProvider and its children from scratch after first reload
// Since, otherwise, the OIDCProvider does not recognize that the config has been updated with the new userStore
// and the session is never stored in the localStorage

  return (
    <OIDCProvider {...config} key={timestamp}>
      {children}
    </OIDCProvider>
  );
}

```

- src/_app.tsx

```tsx
import type { ReactNode } from 'react';
import type { NextPage } from 'next';
import type { AppProps } from 'next/app';
import type { UserConfig } from 'next-i18next';
import { appWithTranslation } from 'next-i18next';
import { ThemeProvider } from 'styled-components';

import '$/yup';

import '$/styles/fonts.css';

import i18nConfig from '$/../next-i18next.config';
import { AuthProvider } from '$/auth/AuthProvider';
import GlobalStyle from '$/styles/global';
import themes from '$/styles/themes';

export type NextPageWithLayout<P = Record<string, unknown>> = NextPage<P> & {
  getLayout?: (page: ReactNode) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function App({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component?.getLayout ?? ((page: ReactNode) => page);

  return (
    <AuthProvider>
      <ThemeProvider theme={themes.light}>
        <GlobalStyle />
        {getLayout(<Component {...pageProps} />)}
      </ThemeProvider>
    </AuthProvider>
  );
}

export default appWithTranslation(App, i18nConfig as UserConfig);

```

- src/pages/login.tsx (from where the method signinPopup is called):

```tsx
import { useAuth } from 'react-oidc-context';

const LoginPage: NextPageWithLayout = () => {
  const auth = useAuth();

  async function handleLogin() {
    await auth.signinPopup();
  }

  return (
      <Container>
          <Title>Login</Title>
          <AccountButton platform={'Microsoft 365'} onClick={handleLogin} />
      </Container>
  );
};
```

- src/pages/index.tsx (the redirect_uri page, which is needed since Next.js shows a 404 error otherwise, thus blocking the auth flow)
 
```tsx
export default function CallbackPage() {
  return <></>;
}
```

### Expected result:

- After entering our credentials, the user session is successfully stored in the local storage, and is also redirected to the /login page (from where it triggered the sign-in flow), and any components calling the `useAuth` hook are re-rendered, since its isAuthenticated flag is now set to true.

### Obtained result:

- After entering our credentials in the Microsoft pop-up (which now occupies the whole window correctly, due to the popupWindowTarget: '_self'), we are kept in the redirect_uri page, with the query params still in it:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/93147810/231411747-2b4ad016-e766-4110-bfeb-998a564570e1.png">

### Workaround #1:

- Avoiding the usage of `popupWindowTarget` in the `AuthProviderProps` eliminates the issue: the user is redirected back to our /login page, with no query params in it, and the user session is stored in the local storage

Nonetheless, this workaround will not work for us, since we don't want a pop-up, but rather a page.

We have also tried replacing `signinPopup` with `signinRedirect` without any additional configuration, but to no avail. It also leaves us in the same redirect_uri (empty) page:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/93147810/231411747-2b4ad016-e766-4110-bfeb-998a564570e1.png">

### Workaround #2:

- Using signinRedirect does work, but only if we remove the localStorage as our chosen store, and let oidc-client-ts use the default sessionStorage

- src/AuthProvider.tsx

```tsx
import type { AuthProviderProps } from 'react-oidc-context';
import { AuthProvider as OIDCProvider } from 'react-oidc-context';

import type { AuthProviderProps } from 'react-oidc-context';

const OIDC_CONFIG: AuthProviderProps = {
  authority: process.env.NEXT_PUBLIC_MICROSOFT_AUTHORITY,
  client_id: process.env.NEXT_PUBLIC_MICROSOFT_CLIENT_ID,
  redirect_uri: process.env.NEXT_PUBLIC_MICROSOFT_REDIRECT_URI,
  popup_redirect_uri: process.env.NEXT_PUBLIC_MICROSOFT_REDIRECT_URI,
  scope: process.env.NEXT_PUBLIC_MICROSOFT_SCOPE,
  refreshTokenAllowedScope: process.env.NEXT_PUBLIC_MICROSOFT_SCOPE,
  post_logout_redirect_uri: process.env.NEXT_PUBLIC_MICROSOFT_REDIRECT_URI,
  response_type: 'code',
};


export function AuthProvider({ children }: AuthProviderProps) {
  return <OIDCProvider {...OIDC_CONFIG}>{children}</OIDCProvider>;
}

```

- src/pages/index.tsx (the redirect_uri page, which is needed since Next.js shows a 404 error otherwise, thus blocking the auth flow)

```tsx
import { useEffect } from 'react';
import { useRouter } from 'next/router';

import { PATHS } from '$/constants/paths';

export default function MicrosoftCallbackPage() {
  const { push } = useRouter();

  useEffect(() => {
    void push(PATHS.HOME);
  }, [push]);

  return <></>;
}

```

Is there something we are missing in our implementation? Our ideal scenario would be to be able to use signinRedirect + localStorage.

Stack used:

- next v13.0.5
- oidc-client-ts v^2.2.2
- react-oidc-context v^2.2.2

**Comment by pamapa** [comment]
First of all `signinPopup` is intended to be used when you want to have a popup window. As you do not want it, do not use it :-)
The `signinRedirect` is for what you want. You will need to provide more details why you can not use `localStorage` and need to use  `sessionStorage`. I am using  `localStorage` + `signinRedirect` successfully.

**Comment by danielmarcano** [comment]
Hi @pamapa, thanks for your fast reply!

Is `localStorage` + `signinRedirect` working for you in a Next.js project? Could you share a snippet showing how you have configured the AuthProvider and passed localStorage as your preferred store?

Either `signinPopup` with `popupWindowTarget: '_self'` or `signinRedirect` works for us.

We first tried with `signinPopup` but seeing that setting `popupWindowTarget` to '_self'  broke the functionality for us, we moved away to `signinRedirect`. That is why I have mentioned both approaches in this issue.

I will create a codesandbox reproducing the issue and link it here so that you can check it out.

**Comment by danielmarcano** [comment]
@pamapa here's a [codesandbox](https://codesandbox.io/p/sandbox/strange-frog-f1ry9g?file=%2F.env&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A3%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A3%7D%5D) where you can reproduce the error.

While developing the codesandbox I realized of a workaround, although since the library is said to handle SSR properly, I still consider that this is a bug.

I have created three different components:

- A `Wrapper`, which makes sure that the entire contents within _app.tsx are only shown after the first render, so the app behaves "like" a client-side-only app. This is actually part of the workaround. Without this wrapper, the session is never stored within the localStorage.

- An `AuthProviderWithoutState`, which which uses `react-oidc-context`'s `AuthProvider` and sets its configuration properties right away, including the userStore as localStorage. This should be wrapped with the `Wrapper` component. Otherwise, the app does not compile as the expected "window is not defined" error is shown.

<img width="979" alt="Captura de pantalla 2023-04-13 a las 21 37 46" src="https://user-images.githubusercontent.com/93147810/231865767-baf4cb7a-3897-4659-8d5d-502d18b7015d.png">

- An `AuthProviderWithState`, which uses `react-oidc-context`'s `AuthProvider` and sets its configuration properties as a state, since window is not defined before the first render. This component can be used with our without `Wrapper`, of course, but it does not work as the auth session is never stored in the `localStorage`, only in the `sessionStorage`.
 
This is basically what the bug is about: with Next.js, it does not seem possible to set `localStorage` as our preferred `userStore`, unless we only show `_app.tsx` after the first render, which is what the `Wrapper` is taking care of. It should be possible to simply set the configuration object as a state, after the initial render...

Just for the sake of brevity, here's the code of the `Wrapper`, the `AuthProviderWithState`, and the `AuthProviderWithoutState`:

- src/wrapper/index.tsx

```tsx
```

- src/auth/index.tsx

```tsx
import { InMemoryWebStorage, WebStorageStateStore } from "oidc-client-ts";
import { useEffect, useState } from "react";
import type { AuthProviderProps } from "react-oidc-context";
import { AuthProvider as OIDCProvider } from "react-oidc-context";

export const OIDC_CONFIG: AuthProviderProps = {
  authority: process.env.NEXT_PUBLIC_AUTHORITY as string,
  client_id: process.env.NEXT_PUBLIC_CLIENT_ID as string,
  redirect_uri: process.env.NEXT_PUBLIC_REDIRECT_URI as string,
  popup_redirect_uri: process.env.NEXT_PUBLIC_REDIRECT_URI as string,
  scope: process.env.NEXT_PUBLIC_SCOPE as string,
  refreshTokenAllowedScope: process.env.NEXT_PUBLIC_SCOPE as string,
  post_logout_redirect_uri: process.env.NEXT_PUBLIC_REDIRECT_URI as string,
  response_type: "code",
  onSigninCallback() {
    window.history.replaceState({}, document.title, window.location.pathname);
  },
};

export function AuthProviderWithState({ children }: AuthProviderProps) {
  const [config, setConfig] = useState<AuthProviderProps>({ ...OIDC_CONFIG });

  useEffect(() => {
    setConfig({
      ...OIDC_CONFIG,
      userStore: new WebStorageStateStore({
        store: window.localStorage ?? InMemoryWebStorage,
      }),
    });
  }, []);

  return <OIDCProvider {...config}>{children}</OIDCProvider>;
}

export function AuthProviderWithoutState({ children }: AuthProviderProps) {
  return (
    <OIDCProvider
      {...{
        ...OIDC_CONFIG,
        userStore: new WebStorageStateStore({
          store: window.localStorage ?? InMemoryWebStorage,
        }),
      }}
    >
      {children}
    </OIDCProvider>
  );
}

```

**Comment by pamapa** [comment]
> window is not defined

I guess you are receiving this error when netxjs pre-renders your application on the server side (SSR). See #414.

**Comment by danielmarcano** [comment]
Thanks for pointing me in the right direction @pamapa.

I had already seen that issue before creating this one, but totally overlooked `globalThis?.` which is what fixes it for me.

I will leave the full fix here, in case it can help anyone else:

```ts
import type { AuthProviderProps } from 'react-oidc-context';
import { AuthProvider as OIDCProvider } from 'react-oidc-context';
import { InMemoryWebStorage, WebStorageStateStore } from 'oidc-client-ts';

import { OIDC_CONFIG } from './constants';

export function AuthProvider({ children }: AuthProviderProps) {
  return (
    <OIDCProvider
      {...OIDC_CONFIG}
      userStore={
        new WebStorageStateStore({
          store: globalThis?.window?.localStorage ?? InMemoryWebStorage,
        })
      }
    >
      {children}
    </OIDCProvider>
  );
}

```
