### ISSUE TITLE
auth.isLoading true when changing routes 

### ISSUE THREAD

**Issue by jnschbrt** [authts/react-oidc-context#737]
I use this library to authenticate via keycloak. the (auto) login/logout works fine.

however, when i change routes within my app, the auth.isLoading state of the useAuth hook is set to "true" for a short time each time i change routes. this is why the loading screen is visible for a short time.

i don't want to check in each useEffect hook beforehand if the isLoading state = false in order to make my axios request and thus set the auth header.

is this intentional? i would have expected this state to be true only if no navigator requests are running or the library is still logging in/out.

I have the following implementation

**Root.tsx**
```
const redirectUri = useRef<string>(`${window.location.origin}/`);

 const authProviderConfig: AuthProviderProps = useMemo(() => {
    return {
      authority: idpUrl,
      client_id: idpClientId,
      redirect_uri: redirectUri.current,
      automaticSilentRenew: true,
      onSigninCallback: () => {
        navigate('/');
      },
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [idpClientId, idpUrl]);

  return (
    <AuthProvider {...authProviderConfig}>
      <StyledEngineProvider injectFirst>
        <CssVarsProvider theme={theme}>
          <CssBaseline />
          <SnackbarProvider
            anchorOrigin={{ horizontal: 'right', vertical: 'top' }}
            Components={{ success: SuccessNotification }}
            maxSnack={1}>
            <App />
          </SnackbarProvider>
        </CssVarsProvider>
      </StyledEngineProvider>
    </AuthProvider>
  );
```

**App.tsx**
```
  const auth = useAuth();

  // automatically sign-in
  useEffect(() => {
    if (!hasAuthParams() && !auth.isAuthenticated && !auth.activeNavigator && !auth.isLoading) {
      auth.signinRedirect();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [auth.isAuthenticated, auth.activeNavigator, auth.isLoading, auth.signinRedirect]);

  switch (auth.activeNavigator) {
    case 'signinSilent':
      return <div>Signing you in...</div>;
    case 'signoutRedirect':
      return <div>Signing you out...</div>;
  }

  if (auth.isLoading) {
    return <div>Loading...</div>;
  }

  if (auth.error) {
    return <ErrorPage error={auth.error.message} />;
  }

  if (auth.isAuthenticated) {
    return (
      <>
        <Routes>
          <Route path="/" element={<Layout />}>
            <Route index element={<Overview />} />
            <Route path="/scheduling" element={<Scheduling />} />
            <Route path="/history" element={<History />} />
            <Route path="/api" element={<API />} />
          </Route>
          <Route path="*" element={<ErrorPage error="404" />} />
        </Routes>
      </>
    );
  }
```

**Comment by pamapa** [comment]
You can track your issue down by looking at the reducer of this library:
https://github.com/authts/react-oidc-context/blob/2d950e4e97a56ae2bce70e054afa4e5793f07bd0/src/reducer.ts#L15-L57

Initially `isLoading` is true and only `NAVIGATOR_INIT` does set it to true...

**Comment by pamapa** [comment]
What probably not so good:
```js
onSigninCallback: () => {
        navigate('/');
      },
```
The code is called when the callback is coming back, your router might not work as expected. Better use `window.history...` as documented here:
https://github.com/authts/react-oidc-context/blob/2d950e4e97a56ae2bce70e054afa4e5793f07bd0/src/AuthProvider.tsx#L30-L44

**Comment by jnschbrt** [comment]
> What probably not so good:
> 
> ```js
> onSigninCallback: () => {
>         navigate('/');
>       },
> ```
> 
> The code is called when the callback is coming back, your router might not work as expected. Better use `window.history...` as documented here:

thanks, did know that - changed that. but i still experience the same problem.


when console.logging the auth.navigator and auth.IsLoading state the same issues occur on every route change:

inside App.tsx
```
const auth = useAuth();
console.log(auth.activeNavigator, auth.isLoading);
```

console output for each click (4 entries):
```
undefined true
undefined true
undefined false
undefined false
```


im using the `{ BrowserRouter } from 'react-router-dom'`. is there any known problem with this one?

**Comment by pamapa** [comment]
> im using the `{ BrowserRouter } from 'react-router-dom'`. is there any known problem with this one?

I'm using the same component without any problem. What i do not do is "automatically sign-in". Have you seen https://github.com/authts/react-oidc-context/issues/485#issuecomment-1232886198?

**Comment by jnschbrt** [comment]
Found the issue.

I was using the <Link href="..."> component from my styling library, instead of the react-router-dom one.
This component actually forced a site refresh/reload, which then initialized the context again, which then refreshed isLoading.
