### ISSUE TITLE
Any way to set response_mode to form_post?

### ISSUE THREAD

**Issue by paulvancoller** [authts/react-oidc-context#738]
In light of Microsoft changes increasing the authorization code size to over 2k for Azure AD B2C, is there any way to configure this package to set response_mode to form_post?

https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad/azure-ad-b2c-authorization-code-and-refresh-token-size-increase/td-p/3770890

We are currently experiencing a situation where the return url is larger than the max allowable length for on Windows or Linux apps services on Azure. 

Any advice would be greatly appreciated.

**Comment by pamapa** [comment]
This library uses oidc-client-ts. I would accept a merge request on that package to extend https://github.com/authts/oidc-client-ts/blob/39566c7699a22336a9e213a2fe788dc577b20f28/src/OidcClientSettings.ts#L77 with `form_post` if its not too invasive...

**Comment by pamapa** [comment]
This issue (question) staled, closing it for now.
