### ISSUE TITLE
An update to AuthProvider inside a test was not wrapped in act(...).

### ISSUE THREAD

**Issue by mironsh** [authts/react-oidc-context#795]
I get the above warning when doing snapshot testing with react-testing-library for components wrapped with AuthProvider.
Any help or direction would be appreciated!

`console.error
    Warning: An update to AuthProvider inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
`

**Comment by pamapa** [comment]
I am seeing the same, this once worked before updating the test libs (jest) incrementally. Would be nice if somebody could fix them...

**Comment by MetaMmodern** [comment]
@pamapa I'm expiriecing the same with vitest

**Comment by jamierytlewski** [comment]
same.

**Comment by thinkedem** [comment]
Still happening with react-oidc-context v2.3.1 / vitest 1.2.0.
