### ISSUE TITLE
Callback does not get handled in Next.js app when using the App router

### ISSUE THREAD

**Issue by mjarosie** [authts/react-oidc-context#807]
Hi,

I'm not sure how to get around the problem. I've got a Next.js application [using the App router](https://nextjs.org/docs/app) and I'm trying to make `react-oidc-context` work with it. What I've got so far (see links to a repo reproducing the issue):

- The only way to wrap the `App` with `AuthProvider` is by placing it in `layout.tsx` (see code [here](https://github.com/mjarosie/react-oidc-context-callback-issue/blob/main/app/layout.tsx#L17))
- `AuthProvider` itself has to be wrapped in a component like so: https://nextjs.org/docs/getting-started/react-essentials#third-party-packages (see code [here](https://github.com/mjarosie/react-oidc-context-callback-issue/blob/main/components/AuthSessionProvider.tsx))

What happens is that the callback is not being handled. [When I `console.log`](https://github.com/mjarosie/react-oidc-context-callback-issue/blob/main/components/AuthSessionProvider.tsx#LL16C14-L16C14) inside `onSigninCallback` nothing gets printed. As a result - the user does not get logged in.

Any hints on how to make it work?

**Comment by pamapa** [comment]
You will need to debug you application + the library code. The underlying oidc-client-ts has a logging system, which can be enabled. See https://authts.github.io/oidc-client-ts/#md:logging

**Comment by joeangry** [comment]
Did you end up figuring this out? I'm currently facing a similar problem to this.

**Comment by mjarosie** [comment]
It had something to do with OAuth Application settings in authorisation server (in my case Keycloak). Let me close the issue.

**Comment by abhilashlr7** [comment]
@mjarosie could you pls provide some inputs on how you had integrated Keycloak and Nextjs app?
