### ISSUE TITLE
Error Handling for failed authentication

### ISSUE THREAD

**Issue by curiosDevInSearch** [authts/react-oidc-context#814]
I cannot find any error handling props in the AuthProvider class, the scenario is after I got redirected back from and there are an issue in the third party sign in, it just return to the redirect url with the a query params of **?error_description=**  is there way of handling any error when doing SSO?

**Comment by pamapa** [comment]
check the event system: https://authts.github.io/oidc-client-ts/#md:events

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
