### ISSUE TITLE
Get Acccess token without using useAuth

### ISSUE THREAD

**Issue by syama-aot** [authts/react-oidc-context#831]
Thanks for excellent library. I need to access the user token without using useAuth hook. is there any method we have

**Comment by pamapa** [comment]
see [readme.md](https://github.com/authts/react-oidc-context): As not a child of AuthProvider (e.g. redux slice) when using local storage (WebStorageStateStore) for the user containing an access token:

**Comment by syama-aot** [comment]
Thanks, I'll check it out.

**Comment by pamapa** [comment]
see above

**Comment by jannnik** [comment]
It might happen that in the localStorage there is an expired token. What is the best practice to prevent expired token to be returned? Is it simply the following, or are there better ways? 

```
  const user = User.fromStorageString(oidcStorage);

  if(user.expired) {
    return null
  }
```

**Comment by pamapa** [comment]
> Is it simply the following, or are there better ways?

Looks good, that is the code within this library: `isAuthenticated: action.user ? !action.user.expired : false` your code aligns with this...
