### ISSUE TITLE
Manually refresh tokens

### ISSUE THREAD

**Issue by Rafael-Ramblas** [authts/react-oidc-context#835]
Hey
First of all I wanna thanks all the people involved in the project.

I was wondering on how can I trigger a token renewal besides using the `startSilentRenew`. 
There's a way to do this using this library, or I would have to force update the storage after calling the renewal endpoint?

Thanks in advance

**Comment by pamapa** [comment]
Using `startSilentRenew` should work

**Comment by Rafael-Ramblas** [comment]
But `startSilentRenew` only updates the token when there is 1 minute left for its expiration. What I want is a way to force update the token, ignoring its exp. Is there a way to force the update, something like `UserManager.updateToken` ?

**Comment by pamapa** [comment]
You are right, i guess auth.[signinSilent()](https://authts.github.io/oidc-client-ts/classes/UserManager.html#signinSilent) is what you want?

**Comment by Rafael-Ramblas** [comment]
It worked, thanks!
