### ISSUE TITLE
"No matching state found in storage" on Reload

### ISSUE THREAD

**Issue by Lasitrox** [authts/react-oidc-context#841]
Hello,
we want to use this Library with Keycloak. I'm having an Issue with reloading the page.
On reload of the page, the following error occurs: No matching state found in storage. When waiting for a few minutes the error goes away, probably on token refresh.

**Comment by susoliaksamuel** [comment]
Please can you elaborate what was incorrect in your use-case ?

**Comment by Lyxass** [comment]
Hi, If anyone faces the same issue, please check that you have correctly implemented the onSigninCallback. Here is an example of implementation (in my main.tsx or index.tsx) : 

```tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'
import {AuthProvider} from "react-oidc-context";
import {Log} from "oidc-client-ts";
import {setTheme, Theme} from "./helper/theme-switch.helper.ts";

const oidcConfig = {
  authority: "https://authority.com/",
  client_id: "clientID",
  redirect_uri: `${window.location}`,
  loadUserInfo: true
};

Log.setLogger(console);

// Got in documentation, you can find this implementation here https://github.com/authts/react-oidc-context/blob/f175dcba6ab09871b027d6a2f2224a17712b67c5/src/AuthProvider.tsx#L20-L30
const onSigninCallback = (): void => {
  window.history.replaceState(
    {},
    document.title,
    window.location.pathname
  )
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <AuthProvider {...oidcConfig} onSigninCallback={onSigninCallback}> // Set the callback here
      <App />
    </AuthProvider>
  </React.StrictMode>,
)
```
I think it would be useful to emphasize this point a little more in the documentation and give a working example

Hoping this will help

**Comment by comod** [comment]
why is this not part of the default instructions?
