### ISSUE TITLE
Keycloak and Storybook

### ISSUE THREAD

**Issue by dmestudent** [authts/react-oidc-context#846]
Hello, 

has anyone managed to get this library working with an app that utilizes Storybook and that authenticates against Keycloak? I managed to get storybook displaying the Keycloak Login Page but after successfully authenticating I am facing the following error. 

"We are sorry... Cookie not found. Please make sure cookies are enabled in your browser."

I assume this is a result of the keycloak login page beeing rendered as an iframe.

I know this issue is rather specific but maybe someone knows a fix/workaround.

Thanks in advance

**Comment by rowellx68** [comment]
I'm not sure how recent the [Storybook instructions for mocking](https://storybook.js.org/docs/writing-stories/mocking-modules#builder-aliases) are, but it worked for us.

The gist is that we had to mock `react-odic-context` and remap the import in Storybook. Our mock looks like this:

```ts
// react-oidc-context.mocks.ts
import { fn } from '@storybook/test';
import {
  AuthProviderUserManagerProps,
  AuthContextProps,
} from 'react-oidc-context';

export const AuthProvider = ({ children }: AuthProviderUserManagerProps) =>
  children;

export const useAuth = fn<[], AuthContextProps>().mockName('useAuth');
```

Then in our story, we do something like below:

```tsx
import { useAuth } from './react-oidc-context.mocks';

// removed for brevity

export const Default: Story = {
  async beforeEach({ args }) {
    useAuth.mockReturnValue({
      isAuthenticated: false,
      isLoading: false,
      signinRedirect: fn().mockName('signinRedirect'),
    } as unknown as AuthContextProps);
  },
};
```

If you use the `user` object in your components, you'll just need to provide one within the `.mockReturnValue`. Something like this maybe?

```ts
useAuth.mockReturnValue({
  isAuthenticated: true,
  user: {
    scopes: ['openid', 'profile', 'email'],
    profile: {
      family_name: 'Smith',
      given_name: 'John',
      name: 'John Smith',
      preferred_username: 'john.smith',
      email: 'john.smith@879607bf-9c3a-4f07-ab12-1eeda9cc34be.com',
      email_verified: true,
    },
  },
} as unknown as AuthContextProps);
```

Hope this helps.

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
