### ISSUE TITLE
Do we need any code changes for GCP migration to complete authentication?

### ISSUE THREAD

**Issue by VijayaSaiRam** [authts/react-oidc-context#850]
Hi team,
could you please guide on this. I am using react-oidc-context library for oauth2.0 which is working well in On-Prem deployment.
**Our project is migrating to GCP. For this, Do we need any code changes to be done for authentication ?**

Actually when we hit the page, after getting the access code <host>/callback?code=<code> , It is not making call to 
token-end point, instead it is giving 404 not found error

Seeking your help regarding this. **Requesting you to look into  this question on high priority**

Thank you  in advance.

**Comment by pamapa** [comment]
Google Identity seems to be still using implicit grant flow, the underlying library (oidc-client-ts) does not support that flow. See https://github.com/authts/oidc-client-ts/issues/152.

**Comment by pamapa** [comment]
if you do not move to Google Identity, ignore my comment. When you move your app from on-premise to GCP and you are still using the same identity provider you do now i do not see any blocker.

**Comment by VijayaSaiRam** [comment]
Thank you for the confirmation: 🙂
