### ISSUE TITLE
Authentication persistance

### ISSUE THREAD

**Issue by gregoirebyvets** [authts/react-oidc-context#852]
Hello everyone, 

I'm trying to make my authentication persistent even if he raech the app from a new browser tab.

(When I reload a authenticated tab, I'm still connected)

I don't find any information about that.

Do you have any clue for me ?

**Comment by pamapa** [comment]
In your oidc settings, this does the trick:
```js
   ...
   userStore: new WebStorageStateStore({ store: window.localStorage }),
```

See https://authts.github.io/oidc-client-ts/interfaces/UserManagerSettings.html#stateStore
