### ISSUE TITLE
dynamic `AuthProvider` props

### ISSUE THREAD

**Issue by pseidemann** [authts/react-oidc-context#855]
hello,

I'm trying to configure `<AuthProvider>` dynamically via values from redux. the problem is, it seems, that once the component is rendered, it cannot be "changed" anymore. adding a `key` prop fixes that a bit, but once I try to log in, I get the "No matching state found in storage" error, probably because of some mismatch of the initial config and the new config.

is there a proper way how to do this?

**Comment by monominia** [comment]
I get the problem as you, and still didn't figure out how to handle it properly.

**Comment by pseidemann** [comment]
hi @pamapa,
could this be considered a bug? I would expect the library to work also when changing the props of the component after first render.

**Comment by monominia** [comment]
Yeah, a simple snippet example provided here:
`
  const [tenantName, setTenantName] = React.useState<string>('') <-- This is what change the props of Provider
  const oidcConfig = {
    authority: `${authUrl}/tenants/${tenantName}`,
    client_id: clientId,
    redirect_uri: `${redirect_host}/login-callback.html`
  }
  return <AuthProvider {...oidcConfig}><div /><AuthProvider />
`

**Comment by pamapa** [comment]
I would accept a patch, which fixes that.

**Comment by pamapa** [comment]
ah, React re-renders when properties change, as you pass `const oidcConfig`, which is passed as property via reference does not change, only its content, it does not re-render, can you try to store the full oidcConfig in that state? I guess that will work.

**Comment by pseidemann** [comment]
@pamapa I tried that and the changes somehow get reflected (login redirect redirects to new url) BUT the state is still the old one resulting in the error message as explained in my initial description, which I think is a bug in this project

**Comment by pseidemann** [comment]
I created https://github.com/authts/react-oidc-context/pull/859 which fixes this issue without the need of a possible big refactoring of the library. instead just allow to skip the provider and once the config is clear, just set the provider with the tenant values

**Comment by pseidemann** [comment]
@monominia to simulate my fix, I wrapped useAuth() in my own function, which catches the exception and just returns undefined
