### ISSUE TITLE
How to obtain Keycloak roles

### ISSUE THREAD

**Issue by ivangfr** [authts/react-oidc-context#872]
Hi, I am planning to replace the [`react-keycloak/web`](https://www.npmjs.com/package/@react-keycloak/web) with [`react-oidc-context`](https://github.com/authts/react-oidc-context)

My app uses **Keycloak**.

It would be interesting to get the roles inside a JWT, so that we can make some controls in the UI (for instance, if the user is an `admin`, shows this menu).

With `react-keycloak/web` we could use something like:
```
keycloak.tokenParsed.resource_access['movies-app'].roles.includes('MOVIES_MANAGER')
```
> **Note**: a sample of Keycloak JWT is show in the end.

However, with `react-oidc-context`, I've been checking the `auth.user.profile` but the `resource_access` is not there. It's understandable, considering `react-oidc-context` is supposed to support many OIDC tools.

Anyway, do you know how could I try to obtain the roles inside a JWT generated by Keycloak?

Best regards,

---

One example of Keycloak JWT Token
```
{
  "exp": 1691445281,
  "iat": 1691444981,
  "auth_time": 1691444980,
  "jti": "90be05cd-1bcc-49d5-a7e4-0db88ab17555",
  "iss": "http://localhost:9080/realms/my-realm",
  "aud": "account",
  "sub": "8931b3ec-e678-4b27-8591-6b02c5a5063d",
  "typ": "Bearer",
  "azp": "my-todo-list",
  "session_state": "ebdac0a7-e659-47d7-91b1-7ebdc613a4d0",
  "acr": "1",
  "allowed-origins": [
    "http://localhost:3000"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization",
      "default-roles-my-realm"
    ]
  },
  "resource_access": {
    "my-todo-list": {
      "roles": [
        "MY-TODO-LIST-USER"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid email profile",
  "sid": "ebdac0a7-e659-47d7-91b1-7ebdc613a4d0",
  "email_verified": true,
  "preferred_username": "app-user",
  "given_name": "",
  "family_name": ""
}
```

**Comment by pamapa** [comment]
Maybe you need to specify `resource` in oidc settings?

**Comment by ivangfr** [comment]
Hi @pamapa . Thanks for answering. I've tried to add the resource in my oidc config:
```
const oidcConfig = {
  authority: "http://localhost:9080/realms/my-realm",
  client_id: "my-todo-list",
  redirect_uri: "http://localhost:3000",
  resource: "my-todo-list",
  onSigninCallback: () => {
    window.history.replaceState(
      {},
      document.title,
      window.location.pathname
    )
  }
}
```

However, I still do not see where I can access the roles

<img width="361" alt="Screenshot 2023-08-15 at 22 18 45" src="https://github.com/authts/react-oidc-context/assets/10564548/c7dd8b25-b7a0-4f22-9fad-7e61331cc6b4">

**Comment by pamapa** [comment]
In order to find out, you will need to log the network request/response of the working library and this library and see where the difference is coming from. Looks like it needs something more, maybe an additional scope or so...

**Comment by mattwcole** [comment]
It looks like by default Keycloak includes roles in the access token but not the ID token and this library uses the ID token to generate the `profile`. You can map roles to a claim in the ID token by adding a mapping to the dedicated scope for your client. Add the `client roles` predefined mapper and then modify it like so.

![image](https://github.com/authts/react-oidc-context/assets/6730646/3c39e455-2d56-48c2-8143-02ffcffbefb1)

**Comment by ivangfr** [comment]
Hi @mattwcole Yes, your suggestion worked! Thanks!

<img width="543" alt="Screenshot 2023-08-21 at 10 02 04" src="https://github.com/authts/react-oidc-context/assets/10564548/b637e8a4-2822-4bb8-aac0-313e84f3da45">

**Comment by pamapa** [comment]
Would be cool if you make a pull request to improve the documentation [here](https://github.com/authts/oidc-client-ts/blob/main/docs/index.md#provider-specific-settings).

**Comment by Tockra** [comment]
> It looks like by default Keycloak includes roles in the access token but not the ID token and this library uses the ID token to generate the `profile`. You can map roles to a claim in the ID token by adding a mapping to the dedicated scope for your client. Add the `client roles` predefined mapper and then modify it like so.
> 
> ![image](https://private-user-images.githubusercontent.com/6730646/261798290-3c39e455-2d56-48c2-8143-02ffcffbefb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NDY3NDEsIm5iZiI6MTcwNzk0NjQ0MSwicGF0aCI6Ii82NzMwNjQ2LzI2MTc5ODI5MC0zYzM5ZTQ1NS0yZDU2LTQ4YzItODE0My0wMmZmY2ZmYmVmYjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMjEzNDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGExYTM5MmQ5OGMyZTJkYzQ3NWE2YmU0NDMwNDcwN2E5MTgyMzZiZGY3OTc2ZjBlMjdjODUwOWJhNzQ3MzRhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l_G6uRwAi-G-0ZdHLzfNisXDtbZTKg6Z1RfOgMj8eTM)

@mattwcole I can't find this setting in the current keycloak 23 version. Do you now where I can find it now?

Is there further a possibility to add the realm roles to the profile ?
My access token looks this way:
```
{
  "exp": 1707947472,
  "iat": 1707947172,
  "auth_time": 1707947171,
  "jti": "5bbd52ea-f3d3-4034-83d7-fddf476c42e8",
  "iss": "http://localhost:8888/realms/test-realm",
  "aud": "account",
  "sub": "e180ffa1-520e-4609-a6e6-f79f93dd5a03",
  "typ": "Bearer",
  "azp": "ember-web",
  "session_state": "55d2f901-74f4-42b9-821e-2cdb8b83dec6",
  "acr": "1",
  "allowed-origins": [
    "http://localhost:3000"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization",
      "default-roles-test-realm"
    ]
  },
  "resource_access": {
    "ember-web": {
      "roles": [
        "SOME_THING"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid email profile",
  "sid": "55d2f901-74f4-42b9-821e-2cdb8b83dec6",
  "email_verified": true,
  "preferred_username": "myUser",
  "email": "tim.tannert@it.financeflow.de"
}
```

I know I could somehow parse the access_token an extract the roles by my own, but isn't there a prettiert solution?

**Comment by christian-draeger** [comment]
have the same problem. since i needed realm_access roles as well as custom claim.
everything is included in the access_token in my case, but oas mentioned by others react-oidc-context useAuth hook will just return standart IdTokenClaims.

## as a workaround i wrote a custom hook (see end of post)

### 🤨 my parsed access token i retrieve from keycloak including `realm_access` `roles` and a custom claim called `store`:
```json
{
  "exp": 1708719399,
  "iat": 1708719099,
  "auth_time": 1708719099,
  "jti": "9e982c2d-18f5-40a9-a5e6-960a7224ccfb",
  "iss": "http://localhost:8180/realms/demo",
  "sub": "cd8da179-2c19-4cf0-aa49-1683a5cf70bf",
  "typ": "Bearer",
  "azp": "webapp",
  "session_state": "a50e7111-24c8-4d90-943c-66466efbe939",
  "acr": "1",
  "allowed-origins": [
    "http://localhost:5173"
  ],
  "realm_access": {
    "roles": [
      "employee"
    ]
  },
  "scope": "openid profile email",
  "sid": "a50e7111-24c8-4d90-943c-66466efbe939",
  "email_verified": false,
  "name": "Elton John",
  "store": [
    "abc"
  ],
  "preferred_username": "elton",
  "given_name": "Elton",
  "family_name": "John",
  "email": "elton@example.com"
}
```


### 😕 what react-oidc-context gives me,
when running:
```typescript
const auth = useAuth();
console.log("user:", auth.user?.profile);
```
result missing `roles` and custom claim `store`:
```json
{
    "exp": 1708721539,
    "iat": 1708721239,
    "iss": "http://localhost:8180/realms/demo-shop",
    "aud": "webapp",
    "sub": "c6dabac0-86bd-4e6a-b6c0-48241a2a4da8",
    "typ": "ID",
    "session_state": "aba63713-ca8d-4af5-9802-c5beff9bad88",
    "sid": "aba63713-ca8d-4af5-9802-c5beff9bad88",
    "email_verified": true,
    "name": "Carl Klammer",
    "preferred_username": "carl",
    "given_name": "Carl",
    "family_name": "Klammer",
    "email": "carl@example.com"
}
```
## as a workaround i came with writing a custom hook that parses the access_token and give me a user object as i need.
### 🧐 custom hook:

```typescript
import {useAuth} from "react-oidc-context";
import {jwtDecode} from "jwt-decode";

type CustomTokenPayload = {
    name: string;
    preferred_username: string;
    given_name: string;
    family_name: string;
    email: string;
    store: string[]; // This is an optional custom claim, some users will have it, some not...
    realm_access: {
        roles: string[];
    };
}

type TokenBaseDetails = Omit<CustomTokenPayload, 'realm_access'>;

type TokenRoles = {
    roles: string[];
}

type TokenDetails = TokenBaseDetails & TokenRoles;

export const useUser = (): TokenDetails | null => {
    const auth = useAuth();

    if (auth.isAuthenticated && auth.user?.access_token) {
        try {
            const decoded = jwtDecode<CustomTokenPayload>(auth.user.access_token);
            return {
                ...decoded,
                roles: decoded.realm_access.roles,
            };
        } catch (error) {
            console.error("Token parsing error:", error);
            return null;
        }
    }

    return null;
};

```

🙂 usage:
```typescript
const user = useUser();
console.log("User:", user);
```

# 🥳
result for user **not having** custom claim `store`:
```
{
    "exp": 1708721539,
    "iat": 1708721239,
    "auth_time": 1708719796,
    "jti": "74acc35a-91c3-4b9d-8386-a6765713ca3a",
    "iss": "http://localhost:8180/realms/demo",
    "sub": "c6dabac0-86bd-4e6a-b6c0-48241a2a4da8",
    "typ": "Bearer",
    "azp": "webapp",
    "session_state": "aba63713-ca8d-4af5-9802-c5beff9bad88",
    "acr": "1",
    "allowed-origins": [
        "http://localhost:5173"
    ],
    "realm_access": {
        "roles": [
            "customer"
        ]
    },
    "scope": "openid profile email",
    "sid": "aba63713-ca8d-4af5-9802-c5beff9bad88",
    "email_verified": true,
    "name": "Carl Klammer",
    "preferred_username": "carl",
    "given_name": "Carl",
    "family_name": "Klammer",
    "email": "carl@example.com",
    "roles": [
        "customer"
    ]
}
```
result for user **having** custom claim `store`:
```json
{
    "exp": 1708722213,
    "iat": 1708721913,
    "auth_time": 1708721913,
    "jti": "82b8d2da-470e-4d45-9b44-1c3de5e7d0bb",
    "iss": "http://localhost:8180/realms/demo",
    "sub": "cd8da179-2c19-4cf0-aa49-1683a5cf70bf",
    "typ": "Bearer",
    "azp": "webapp",
    "session_state": "975d96e8-8b8e-4ca4-8f77-75b6ca2b18ea",
    "acr": "1",
    "allowed-origins": [
        "http://localhost:5173",
    ],
    "realm_access": {
        "roles": [
            "employee"
        ]
    },
    "scope": "openid profile email",
    "sid": "975d96e8-8b8e-4ca4-8f77-75b6ca2b18ea",
    "email_verified": false,
    "name": "Elton John",
    "store": [
        "abc"
    ],
    "preferred_username": "elton",
    "given_name": "Elton",
    "family_name": "John",
    "email": "elton@example.com",
    "roles": [
        "employee"
    ]
}
```


## 🤞 Maybe it will help someone
