### ISSUE TITLE
Safari download an empty logout file when I use signoutSilent method

### ISSUE THREAD

**Issue by gregoirebyvets** [authts/react-oidc-context#883]
Hello guys,

I'm quite newbie with oidc and I have an issue that I dont understand.

On Safari, when a user click on the "Logout" button (wich use signoutSilent() ), the browser ask if I want to download the "logout" file (from Keycloak logout url)

Do you know why I'm facing this ?

Thanks

**Comment by gregoirebyvets** [comment]
Here is my ui button code.

` <HeaderButton onClick={() => auth.signoutSilent()}>
                        Log out
                </HeaderButton>`

**Comment by pamapa** [comment]
How does it look like rendered is it a `<a>` tag, which Safari reacts with download. Maybe try something else?

**Comment by gregoirebyvets** [comment]
It's actually a button:

`<button tabindex="-1" class="bg-trinidad-500 font-normal text-white rounded-full px-3 py-2 mx-2 lg:px-6 lg:py-2 lg:mx-2 text-sm lg:text-base">Log out</button>`

**Comment by pamapa** [comment]
no idea, you will need to track it down, does that button + `onClick` with a `console.log("aha")` and no `auth.signoutSilent()` also trigger the download?

**Comment by gregoirebyvets** [comment]
Ok thanks for your help, I'll investigate deeper and give a feedback if I find anything relevant
