### ISSUE TITLE
Up to date documentation for implementing Keycloak 22 with React

### ISSUE THREAD

**Issue by MylesWardell** [authts/react-oidc-context#884]
#### Issue
I am looking for up to date guides or example builds of using this package now the @react-keycloak/web is deprecated. 

Alternatively, can somebody link me to maybe something open source that implements something similar?

**Comment by pamapa** [comment]
You can search here and in the underlying libraries project side [here](https://github.com/authts/oidc-client-ts) using the label filter `label:"Keycloak Identity"`

**Comment by pamapa** [comment]
Would be wonderful when you managed to make it work, when you document it with a MR here: https://github.com/authts/oidc-client-ts/blob/main/docs/index.md#provider-specific-settings

**Comment by MylesWardell** [comment]
Can I just confirm that keycloak 22 works with this library? Does it work in strict mode? My team is running into issues where we get redirected back to the application but the internal library does not save user data or save authentication state.

Potential issues
- Version -> We are using keycloak 22
- Strict mode -> We are using latest version of react with strict mode
- Keycloak config -> 
![image](https://github.com/authts/react-oidc-context/assets/55673046/112905be-0dcc-4b50-817a-7fa1f4149589)
- Parcel -> We use parcel to build the frontend
- Does the context hook need to be outside router? I have tried both in and out both with the same error

Here is the config
```typescript
const oidcConfig: React.ComponentProps<typeof AuthProvider> = {
  authority: 'http://localhost:9000/realms/local',
  client_id: 'react-frontend',
  redirect_uri: 'http://localhost:1234',
  loadUserInfo: true,
}

const Authentication = (props: Props) => {
  const { children } = props
  const redirect = useNavigate()

  return (
    <AuthProvider
      {...oidcConfig}
      onSigninCallback={() => {
        redirect('deposits')
      }}
    >
      {children}
    </AuthProvider>
  )
}
```

When going to signinRedirect we enter username and password correctly and get redirected back with this query param
![image](https://github.com/authts/react-oidc-context/assets/55673046/3e441d1d-d0d3-4bfa-b1e7-1fe5dd644cad)
```http://localhost:1234/?state=3614d7f976274a6593a9a491f751c07e&session_state=021f40ad-fa0c-4914-9a0c-a01476b60444&code=9def48fc-7d7f-45e3-8f3d-410c2f1df394.021f40ad-fa0c-4914-9a0c-a01476b60444.843662a7-155d-4c81-a9df-3d414a9eb098```

Then when logging out status everything is undefined and null
![image](https://github.com/authts/react-oidc-context/assets/55673046/86280e1b-fa31-4596-9f22-6f4cf389100a)

Here are the logs before and after login click with successfull auth
![image](https://github.com/authts/react-oidc-context/assets/55673046/dae1c8bd-e3f0-4193-9c74-c91757ed7564)

**Comment by pamapa** [comment]
> My team is running into issues where we get redirected back to the application but the internal library does not save user data or save authentication state.

1:
When the redirect is coming back it must match the previously stored state. In order to see that, its easier to [enable logging](https://authts.github.io/oidc-client-ts/#md:logging).

Interesting code:
https://github.com/authts/oidc-client-ts/blob/5e808996f1c25d2c211069616809cd274c5f5b6d/src/OidcClient.ts#L141-L159

2:
Have you looked into [userStore](https://authts.github.io/oidc-client-ts/interfaces/UserManagerSettings.html#userStore) setting? Also see [stateStore](https://authts.github.io/oidc-client-ts/interfaces/OidcClientSettings.html#stateStore)
By default the underyling library (oidc-client-ts) is using sessionStorage, but when using multiple TABs that would be not good enough...
```js
const oidcConfig: AuthProviderProps = {
    ...
    userStore: new WebStorageStateStore({ store: window.localStorage }),
};
```

**Comment by MylesWardell** [comment]
1. I am not receiving anything in the error console that has these errors 
![image](https://github.com/authts/react-oidc-context/assets/55673046/162820b5-d6ea-4b7e-927c-3b13624c70b4)

Right after I authenticate on keycloak I imediatly call the client port
![image](https://github.com/authts/react-oidc-context/assets/55673046/ae9ef558-e8d9-4539-a825-de6d1fff920a)
![image](https://github.com/authts/react-oidc-context/assets/55673046/56c72d91-d99d-45fe-bd20-aa771b04cd65)

2. I added these settings to my config and it did not improve anything

**Comment by pamapa** [comment]
You will have to debug that. Does `readSigninResponseState` get called, if not search through the code where its called, ...

**Comment by MylesWardell** [comment]
We gave up on using this library building a custom context hook using keycloak-js. Closing this ticket. 

If your experiencing issues we used keycloak quick start spa app as an example realm config  + code
