### ISSUE TITLE
'Refused to frame' error when calling silentSignin

### ISSUE THREAD

**Issue by ryan-wheatley** [authts/react-oidc-context#888]
Hey, I'm getting the following console errors when attempting a silent sign in in my nextjs app using the app router.

`[Report Only] Refused to frame 'https://auth.fnty.dev/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

`Refused to display 'https://auth.fnty.dev/' in a frame because it set 'X-Frame-Options' to 'deny'.` 

https://auth.fnty.dev is the `authority` for my `AuthProvider` props. I am trying to use `react-oidc-context` with Ory. My openid config https://auth.fnty.dev/.well-known/openid-configuration if thats any help. 

I am at a bit of a loss as to what could be causing this, any advice would be greatly appreciated. Thanks, Ryan

**Comment by pamapa** [comment]
Looks like a CSP/CORS error. You will need to configure the "Content-Security-Policy" for responses in your application. Respectively its probably whats our application configures with "X-Frame-Options".

**Comment by ryan-wheatley** [comment]
Thank you!
