### ISSUE TITLE
Infinite loop after logging in when protecting all routes

### ISSUE THREAD

**Issue by MarkvV** [authts/react-oidc-context#904]
We are using this library with Keycloak. We are trying to implement it right now in such a way that you don't have a separate login page. Meaning that if you enter anywhere in the website you get redirected to login. This works like a charm. However once logged in and redirected back we get an infinite loop where the ?state= variable gets updated all the time. We don't know what causes this behaviour and wonder if this flow is supported by any means? Or should you always have a landing page, i.e. login page or dashboard of some kind?

**Comment by pamapa** [comment]
You will do find out what cases the infinite loop, you can do so by (adding logging)[https://authts.github.io/oidc-client-ts/#md:logging].  Its most probably some logic in your application, hard to guess what... Make sure to clean properly the URL after successfully logged in, [see](https://github.com/authts/react-oidc-context/blob/6368da161514de62b22c26bdb59cc9b1d50cca06/src/AuthProvider.tsx#L30-L43)

**Comment by MarkvV** [comment]
Thanks. Logging is added and the following error is presented before redirecting every time `[UserManager] getUser: user not found in storage`. We also tried to clean the URL after logging in, as you mentioned.

Any suggestions?

**Comment by pamapa** [comment]
You will need to find out why the user is not stored (`[UserManager] getUser: user not found in storage`), looks like the authentication process did not finish. Typically when the redirect request is coming from the authz the previously stored session must be found and matched, [see](https://github.com/authts/oidc-client-ts/blob/d1c9354bf5289a878c262090ea5f7f31de697fb7/src/OidcClient.ts#L141-L159)

**Comment by MarkvV** [comment]
When we introduce a page without authentication. There is actually now problem and we get logged in just fine. However we don't want this. I think we want the flow as described in the README as `Automatic sign-in`.

Also we noticed that the localStorage fills up with session-ids and sessionStorage is empty. We also tried to place a debug point in the code you mentioned `readSigninResponseState`, however the redirect/refresh happens faster than we hit the debug point.

To be complete, this is how our auth provider props looks like:
```
const configuration: AuthProviderProps = {
    scope: "openid profile email",
    client_id: "<client_id>",
    authority: "<authority>",
    redirect_uri: "http://localhost:3000/",
    userStore: new WebStorageStateStore({ store: window.localStorage }),
    onSigninCallback: () => {
        window.history.replaceState({}, document.title, window.location.pathname);
    },
};
```
