### ISSUE TITLE
When providing a client_secret in the AuthProviderProps it is not used in the token request

### ISSUE THREAD

**Issue by DemianQuad** [authts/react-oidc-context#905]
Seems that when i provide a client_secret in the AuthProviderProps its doesn't show up in the token request. therefore failing the request. Is this a known bug or am i doing something wrong?

this is my config:
```
const configuration: AuthProviderProps = {
    scope: "openid profile email",
    client_id: Env.OAUTH2_CLIENT_ID,
    client_secret: Env.OAUTH2_CLIENT_SECRET,
    authority: Env.OAUTH2_ISSUER,
    redirect_uri: Env.OAUTH2_REDIRECT_URI,
    onSigninCallback: () => {
        window.history.replaceState({}, document.title, window.location.pathname);
    },
};
```

**Comment by DemianQuad** [comment]
Hey, thanks for the response. I have tried both options of that setting. sadly none seem te cause the secret being added to the formdata send with the token request

**Comment by pamapa** [comment]
You will need to debug down the rabbit hole...
