### ISSUE TITLE
No matching state found in storage

### ISSUE THREAD

**Issue by Leighton88** [authts/react-oidc-context#910]
Hi

I understand this is a wrapper library for the oidc-client-ts. However if i run my reactjs application under the root i.e. https:\\localhost\ the sign in works as expected i.e. contacts the Identity server and handles the response correctly.

The issue i have is that i have to install this under a sub folder i.e. Https:\\localhost\SubFolder\

When doing so the identity server is contacted and a response issues. The issue lies when the library giving back an authorisation error 

No matching state found in storage

having looked at the storage i can see the oidc settings stored what looks correctly. Is there something i need to do differently for running this under a sub folder?

Thanks

**Comment by susoliaksamuel** [comment]
@Leighton88 Hello, I ran into a similar issue lately. It seems to me that the problem was in the fact that I was accessing the app via `127.0.0.1:<port> `url and my redirect URI was set to `localhost:<port>`.

**Comment by Lyxass** [comment]
Hey @Leighton88, I had a similar issue today. I forgot to implement the signinCallback causing the "No matching state found in storage" error. Maybe this comment will help you: https://github.com/authts/react-oidc-context/issues/841#issuecomment-1740973579

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
