### ISSUE TITLE
How to force renew an access token?

### ISSUE THREAD

**Issue by raubel** [authts/react-oidc-context#914]
Hi,

I'm using react-oidc-context with keycloak.
From the webapp, I call the keycloak  Admin REST API to create a realm and then administer that realm (to add users for instance).

The access token emitted by keycloak (`useAuth`) has only the permissions to manage the realms that existed when it was generated (even if the associated user is the keycloak super-admin). 
So, I need a new token after the new realm has been created to be able to add users.

I tried to revoke the access token (calling `auth.revokeToken(["access_token"])`, but a new token is not requested right away. I need to wait some time (probably until my previous (revoked) token is expired).

Is it possible to get a new token on demand?

Thanks for any advice.

**Comment by pamapa** [comment]
See https://github.com/authts/oidc-client-ts/issues/1073#issuecomment-1619743018

**Comment by raubel** [comment]
Thank you @pamapa, it is exactly what I am looking for.
