### ISSUE TITLE
auth events are not triggering ?

### ISSUE THREAD

**Issue by syama-aot** [authts/react-oidc-context#916]
Thanks for excellent library.  I need to update the user login activity based on the user signIn or user loading event. I tried following code. But I am not getting any console. This is my authConfig file 

const authConfig = {
  client_id: config.keycloak_clientid,
  authority: config.keycloak_url + "realms/" + config.keycloak_realm,

  automaticSilentRenew: true,
  monitorSession: true,
};

  React.useEffect(() => {
    console.log("company", auth?.events);
    const handleUserLoaded = (user) => {
      console.log("user Loaded", user);
    };

 
    return auth.events?.addUserLoaded(handleUserLoaded);

  }, [auth.events]); hanldeUserLoaded is not calling at all. What was the issue

**Comment by pamapa** [comment]
This library already handles the `addUserLoaded`, what is does is dispatch the user object, which will work togther with `userAuth`, the later will trigger a re-render. In case you need more/something else you can register on the underlying library using `auth.events.addUserLoaded`. See https://authts.github.io/oidc-client-ts/#md:events
