### ISSUE TITLE
User Unauthorization when the page is Reloaded.

### ISSUE THREAD

**Issue by nahugomez** [authts/react-oidc-context#948]
I’m trying to implement an `<AuthGuard>` component in my React application, which allows the user to access certain routes based on whether they are authenticated, and whether they have the roles enabled to do so. It’s important to clarify that I’m using version 6 of **React Router Dom** for route management.

The implementation of the component works correctly, there’s just one detail. If the user is logged in, and they are on a protected route, if for some reason they reload the page, they are redirected to _“/unauthorized”_. Then, if the user navigates using the `<Link>` from React Router Dom, they have the possibility to access that protected route, without having to log in again.

The following code corresponds to the implementation of `<AuthGuard>
`
```
import { useEffect } from 'react';
import { Navigate, Outlet } from 'react-router-dom';
import { useAuth } from 'react-oidc-context';
import PublicRoutes from './PublicRoutes';
import PropTypes from 'prop-types';
import jwtDecode from 'jwt-decode';
import ResourceRealms from './ResourceRealms';

const AuthGuard = ({ allowedRoles }) => {
  const { isAuthenticated, user, signinSilent } = useAuth();
  useEffect(() => {
    if (!isAuthenticated) {
      signinSilent();
    }
  }, []);

  if (!isAuthenticated) {
    return <Navigate replace to={`/${PublicRoutes.UNAUTHORIZED}`} />;
  }

  if (allowedRoles && allowedRoles.length > 0) {
    const decodedToken = jwtDecode(user.access_token);
    const hasRole = allowedRoles.some(role =>
      decodedToken.resource_access[ResourceRealms.APPLICATION].roles.includes(role),
    );
    if (!hasRole) {
      return <Navigate replace to={`/${PublicRoutes.UNAUTHORIZED}`} />;
    }
  }

  return <Outlet />;
};

export default AuthGuard;
```

How can I make it so that the user, when they are on a protected route and reload the page, is not redirected to _“/unauthorized”_?

**Comment by kainbryanjones** [comment]
I believe you can use the 'isLoading' prop

```ts
  const { isAuthenticated, user, signinSilent, isLoading } = useAuth();
```

while isLoading is true you're checking whether the user is authenticated or not

so perhaps something like this

```ts
if (isLoading) return <Spinner/>
///then under this put your auth handling logic 
```
