### ISSUE TITLE
Single sign out browser wide

### ISSUE THREAD

**Issue by Itzmeamario** [authts/react-oidc-context#963]
I've logged in successfully using Google SSO, but when using `auth.signoutPopup()` I get logged out from all websites and from all Gmail accounts logged in at the moment.
Is there something I'm missing?

**Comment by pamapa** [comment]
I do not know the behavior of Google Indenity. Maybe be this helps you https://github.com/authts/oidc-client-ts/pull/1038/files#diff-c833a002f3fa487666ed42d9742ea5ae2fa4ada00227943616583ed0c3204120 (adding client_id) or you need to pass the `id_token_hint` into  `auth.signoutPopup()`, maybe both does not work. You will need to read the spec of Google Indenity

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
