### ISSUE TITLE
Single Sign out browser level.keycloak 

### ISSUE THREAD

**Issue by syama-aot** [authts/react-oidc-context#972]
Thanks for wonderful library. I used for Keycloak integration. Overall, it's been working well. I've implemented local storage for storing data. However, when I log out in one tab, it doesn't automatically log me out in other open tabs. If I refresh the page, it correctly redirects to the login page. The issue arises when I perform actions without refreshing; it results in errors. I'm looking for a solution to achieve browser-level logout. Thanks.

**Comment by pamapa** [comment]
Have you seen https://github.com/authts/react-oidc-context/issues/792#issuecomment-1611690087?

**Comment by syama-aot** [comment]
> Have a look at [#792 (comment)](https://github.com/authts/react-oidc-context/issues/792#issuecomment-1611690087)

It's working for single tab.not for all tabs

**Comment by Chrisdo82** [comment]
Is there a workaround until 3.0.0 gets released?

**Comment by pamapa** [comment]
You can simply use the 3.0.0-rc.1.  I plan to release the 3.0.0 in a few days though.
