### ISSUE TITLE
Implement auth only on some routes

### ISSUE THREAD

**Issue by eugeniosegala** [authts/react-oidc-context#993]
Hello,

I was wondering if it's possible to only protect some routes of an application.

From what I can see, the `AuthProvider` wraps the entire application so soon as anything renders, the user will be redirected to the login page.

In my case, I have a variety of public/private pages.

Would it be possible to decide on which pages we want to trigger the login session?

**Comment by pamapa** [comment]
> Would it be possible to decide on which pages we want to trigger the login session?

Sure, the application has full control, see https://github.com/authts/react-oidc-context#getting-started

````tsx
if (auth.isAuthenticated) { // you can define where you want to have this...
        return (
        <div>
            Hello {auth.user?.profile.sub}{" "}
            <button onClick={() => void auth.removeUser()}>Log out</button>
        </div>
        );
    }
````

**Comment by eugeniosegala** [comment]
> https://github.com/authts/react-oidc-context#getting-started

Oh I see what you mean!

I can call the `signinRedirect` on a `useEffect` on the pages I want to be under auth!

That makes sense, thank you!
